--Villains
        ["AA Attuma"] = {vp=1, isVillain=true, cost=2, id=1336},
        ["R5 Songbird"] = {vp=1, isVillain=true, cost=3,},
        ["R1 Venom"] = {vp=1, isVillain=true, cost=4, id=4124},
        ["TU M.O.D.O.K."] = {vp=1, isVillain=true, cost=2, id=4500},
        ["CO9 High Evolutionary"] = {vp=2, isVillain=true, isDefense=true, cost=6,},
        ["R4 Blob"] = {vp=1, isVillain=true, cost=3,},
        ["R5 Blazing Skull"] = {vp=1, isVillain=true, cost=3,},
        ["IW5 Carnage Werewolf"] = {vp=3, isVillain=true, cost=6,},
        ["R5 Proxima Midnight"] = {vp=1, isVillain=true, cost=3,},
        ["RC Shriek"] = {vp=1, isVillain=true, isDefense=true, cost=5,},
        ["TU Hatemonger"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=9000},
        ["CO11 Viper"] = {vp=1, isVillain=true, cost=5,},
        ["CC1 Scorpion"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
        ["R2 Blastaar"] = {vp=2, isVillain=true, isDefense=true, cost=6, id=4743},
        ["KIB Archangel"] = {vp=2, isVillain=true, isMetal=true, isAttack=true, cost=7, id=3061},
        ["CC1 Yellowjacket"] = {vp=1, isVillain=true, isAttack=true, cost=4,},
        ["Marvel Thunderbolts"] = {vp=0, isVillain=true, cost=4, id=9516},
        ["R4 Black Mamba"] = {vp=2, isVillain=true, cost=4,},
        ["R5 Vulture"] = {vp=1, isVillain=true, cost=2,},
        ["RC Venom"] = {vp=2, isVillain=true, cost=7,},
        ["TV Tinkerer"] = {vp=1, isVillain=true, cost=2, isOngoing=true, isBribe=true,},
        ["R5 Impossible Man"] = {vp=2, isVillain=true, cost=6,},
        ["RC Vermin"] = {vp=1, isVillain=true, isBribe=true, cost=2,},
        ["R5 Hulk World War"] = {vp=1, isVillain=true, cost=5,},
        ["IW5 Hobgoblin"] = {vp=0, isVillain=true, cost=5,},
        ["CW Blackheart"] = {vp=1, isVillain=true, cost=3, id=3500},
        ["CO7 The Fallen One"] = {vp=1, isVillain=true, cost=5, id=7900},
        ["CW2 Symbiote Spider-man"] = {vp=1, isVillain=true, isDefense=true, cost=2,},
        ["CW Titania"] = {vp=1, isVillain=true, isDefense=true, cost=3, id=5897},
        ["MARVEL Jigsaw"] = {vp=1, isVillain=true, cost=2, id=1319},
        ["TU Kang"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=1316},
        ["CO11 Carnage"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
        ["CO9 Elektra"] = {vp=1, isVillain=true, isAttack=true, cost=3,},
        ["KIB Magneto"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=2013},
        ["R3 Zombie Quicksilver"] = {vp=3, isVillain=true, isAttack=true, cost=7,},
        ["TU Nebula"] = {vp=1, isVillain=true, isOngoing=true, cost=4, id=9940},
        ["DA Supergiant"] = {vp=1, isVillain=true, cost=3, id=4630},
        ["RC Mad Thinker"] = {vp=1, isVillain=true, isBribe=true, cost=4,},
        ["TU Rhino"] = {vp=1, isVillain=true, cost=3, id=4158},
        ["IW2 Zombie Namor"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=9302},
        ["TU90 Pets of Evil Masters"] = {vp=1, isVillain=true, cost=2, id=8228},
        ["TV Muse"] = {vp=1, isVillain=true, cost=3, isBribe=true,},
        ["RC Prowler"] = {vp=1, isVillain=true, isBribe=true, cost=3,},
        ["RC Pyro"] = {vp=1, isVillain=true, isAttack=true, isBribe=true, cost=4,},
        ["CO2 Blade"] = {vp=1, isVillain=true, cost=5, id=6557},
        ["CO9 Viper"] = {vp=2, isVillain=true, isAttack=true, cost=5,},
        ["CO11 Elektra"] = {vp=1, isVillain=true, cost=4,},
        ["IW5 Oblivion"] = {vp=3, isVillain=true, cost=6,},
        ["TU Wendigo"] = {vp=1, isVillain=true, isDefense=true, cost=5, id=6650},
        ["KIB Man-Spider"] = {vp=2, isVillain=true, cost=2, id=8624},
        ["CW Abomination"] = {vp=1, isVillain=true, cost=5, id=4747},
        ["R4 Pestilence"] = {vp=2, isVillain=true, isAttack=true, isConfrontation=true, cost=6,},
        ["R2 Ego the Living Planet"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=4516},
        ["RC Juggernaut"] = {vp=1, isVillain=true, isDefense=true, cost=4,},
        ["RC Leap-Frog"] = {vp=1, isVillain=true, isBribe=true, cost=5,},
        ["TV Red Skull"] = {vp=2, isVillain=true, cost=5, isAttack=true,},
        ["TU Mole Man"] = {vp=1, isVillain=true, isDefense=true, isOngoing=true, cost=2, id=5859},
        ["CO5 Molten Man"] = {vp=0, isVillain=true, cost=3, id=5922},
        ["TU902 Forbush Man"] = {vp=1, isVillain=true, cost=5,},
        

--Heroes
        ["CW Moon Knight"] = {vp=1, isHero=true, cost=3, id=7178},
        ["R4 Armor"] = {vp=2, isHero=true, isDefense=true, cost=5,},
        ["RC Night Thrasher"] = {vp=1, isHero=true, cost=5,},
        ["R4 Freyja"] = {vp=2, isHero=true, isBlock=true, blockValue=3, cost=5,},
        ["IW Northstar"] = {vp=1, isHero=true, isOngoing=true, cost=4, id=1791},
        ["RC Jessica Jones"] = {vp=1, isHero=true, isBribe=true, cost=3,},
        ["RC Iron Patriot"] = {vp=2, isHero=true, cost=6,},
        ["CW Cosmo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5000},
        ["R5 Cosmo"] = {vp=1, isHero=true, cost=4,},
        ["RC Linda Carter"] = {vp=1, isHero=true, cost=4,},
        ["CW2 Black Widdow"] = {vp=1, isHero=true, isAttack=true, cost=3,},
        ["IW5 Jeff"] = {vp=2, isHero=true, isDefense=true, cost=7,},
        ["CO11 Daredevil"] = {vp=1, isHero=true, cost=5,},
        ["SW Namor"] = {vp=1, isHero=true, cost=3, id=1049},
        ["CO11 Hawkeye"] = {vp=2, isHero=true, cost=4,},
        ["IW5 Adam Warlock"] = {vp=3, isHero=true, isDefense=true, cost=8,},
        ["RC Devil DInossaur"] = {vp=1, isHero=true, isDefense=true, cost=3,},
        ["TV Valkyrie"] = {vp=1, isHero=true, cost=4, isOngoing=true, isBribe=true,},
        ["CW Triton"] = {vp=1, isHero=true, cost=3, id=6213},
        ["TV The Thing"] = {vp=2, isHero=true, cost=6, isBribe=true,},
        ["R4 Howard the Duck"] = {vp=1, isHero=true, isDefense=true, cost=4,},
        ["TV Goose"] = {vp=1, isHero=true, cost=5, isOngoing=true, isDefense=true,},
        ["IW5 Youndu"] = {vp=2, isHero=true, cost=5,},
        ["R3 Silk"] = {vp=1, isHero=true, cost=4,},
        ["IW2 Mar-Vell"] = {vp=1, isHero=true, cost=4, id=6613},
        ["R3 Iceman"] = {vp=1, isHero=true, isAttack=true, cost=4,},
        ["CO9 Falcon"] = {vp=1, isHero=true, isAttack=true, cost=4,},
        ["RC Hellcat"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=5,},
        ["AS Adam Warlock"] = {vp=2, isHero=true, cost=7, id=7644},
        ["CO10 Earth X Namora"] = {vp=-2, isHero=true, isDefense=true, isTimeLineUp=true, cost=6,},
        ["MS Dr. Michael Morbius"] = {vp=1, isHero=true, cost=4,},
        ["TU Drax"] = {vp=1, isHero=true, cost=4, id=7267},
        ["RC Sunspot"] = {vp=1, isHero=true, isDefense=true, cost=4,},
        ["R1 Miles Morales"] = {vp=1, isHero=true, cost=4, id=5295},
        ["CW Midnight Sons"] = {vp=1, isHero=true, isDefense=true, cost=3, id=6352},
        ["RC Misty Knight"] = {vp=2, isHero=true, cost=6,},
        ["SW2 Thor Jane Foster"] = {vp=2, isHero=true, isDefense=true, cost=6,},
        ["SW Eve Bakian nova corp"] = {vp=1, isHero=true, cost=4, id=1285},
        ["TV Ghost Rider"] = {vp=1, isHero=true, cost=3, isBribe=true,},
        ["R5 Ironheart"] = {vp=2, isHero=true, cost=5,},
        ["KIB Mr. Fantastic"] = {vp=1, isHero=true, cost=3, id=6084},
        ["MARVEL Deadpool"] = {vp=1, isHero=true, cost=3, id=6872},
        ["DA Ironheart"] = {vp=1, isHero=true, cost=3, id=8620},
        ["DA Wave"] = {vp=1, isHero=true, cost=2, id=1728},
        ["CO11 Nighttrasher"] = {vp=1, isHero=true, cost=4,},
        ["CO1 Iron Fist"] = {vp=1, isHero=true, cost=4, id=6666},
        ["IW4 Blink"] = {vp=2, isHero=true, isOngoing=true, cost=6, id=8216},
        ["SW Deadpool"] = {vp=0, isCharacter=true, id=7597},
        ["TU Sunfire"] = {vp=1, isHero=true, cost=2, id=9694},
        ["R5 Cyclops"] = {vp=2, isHero=true, cost=6,},
        ["IW5 Domino"] = {vp=2, isHero=true, cost=5,},
        ["DA Maria Hill"] = {vp=1, isHero=true, cost=4, id=8153},
        ["R5 Trish Tilby"] = {vp=1, isHero=true, cost=2,},
        ["RC Moon Knight"] = {vp=1, isHero=true, cost=4,},
        ["R3 Cannonball"] = {vp=1, isHero=true, cost=3,},
        ["AA Spider-Gwen"] = {vp=1, isHero=true, cost=3, id=9385},
        ["R5 Cyclops"] = {vp=1, isHero=true, cost=5,},
        ["R4 Falcon"] = {vp=1, isHero=true, isDefense=true, cost=5,},
        ["RC Prison Guard"] = {vp=1, isHero=true, isBribe=true, cost=1,},
        ["CO1 Squirel Girl"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5755},
        ["RC America Chavez"] = {vp=2, isHero=true, isBribe=true, cost=7,},
        ["AA Psylocke"] = {vp=1, isHero=true, isDefense=true, cost=2, id=6046},
        ["R4 Hercules"] = {vp=1, isHero=true, isConfrontation=true, cost=5,},
        ["CO10 Earth X Captain Britain"] = {vp=-2, isHero=true, isTimeLineUp=true, cost=5,},
        ["R2 The Watcher"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7874},
        ["TU Namorita"] = {vp=1, isHero=true, isOngoing=true, cost=3, id=4487},
        ["IW4 Valkyrie"] = {vp=2, isHero=true, isDefense=true, cost=6, id=9723},
        ["TU Multiple Man"] = {vp=1, isHero=true, cost=2, id=1767},
        ["CW Havok"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9933},
        ["TU90 Cyclops"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7161},
        ["RC Happy Hogan"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=3,},
        ["AA Jean Grey"] = {vp=1, isHero=true, cost=3, id=8883},
        ["IW1 Wolverine"] = {vp=1, isHero=true, cost=5, id=8902},
        ["CW Brother Voodoo"] = {vp=1, isHero=true, cost=3, id=6429},
        ["R5 Betty Ross"] = {vp=1, isHero=true, cost=2,},
        ["R5 She-Hulk"] = {vp=2, isHero=true, cost=7,},
        ["CO11 Vision"] = {vp=2, isHero=true, cost=6,},
        ["TU 90-2 Doop"] = {vp=1, isHero=true, cost=4,},
        ["IW5 Jean Grey"] = {vp=2, isHero=true, isDefense=true, cost=6,},
        ["CO3 Quasar"] = {vp=1, isHero=true, cost=5, id=6299},
        ["SW3 Wolverine"] = {vp=1, isHero=true, cost=5,},
        ["CO11 Spider-man"] = {vp=1, isHero=true, cost=3,},
        ["CC1 Dust"] = {vp=1, isHero=true, isDefense=true, cost=4,},
        ["IW5 Whizzer"] = {vp=2, isHero=true, cost=7,},
        ["CO12 Micro"] = {vp=1, isHero=true, cost=2,},
        ["TU Blue Marvel"] = {vp=1, isHero=true, isDefense=true, cost=4, id=5808},
        ["R4 Polaris"] = {vp=1, isHero=true, isBlock=true, blockValue=2, cost=4,},
        ["DA Rachel Summers"] = {vp=1, isHero=true, isDefense=true, cost=4, id=8676},
        ["R3 Speed"] = {vp=2, isHero=true, cost=5,},
        ["RC Symbie"] = {vp=1, isHero=true, cost=2,},
        ["CO11 Human Torch"] = {vp=2, isHero=true, cost=5,},
        ["R1 War Machine"] = {vp=1, isHero=true, cost=3, id=7521},
        ["CW2 Daredevil"] = {vp=2, isHero=true, isDefense=true, cost=6,},
        ["R5 Mary Jane"] = {vp=1, isHero=true, cost=4,},
        ["R2 Phyla-Vell"] = {vp=1, isHero=true, cost=3, id=5209},
        ["R5 Rogue"] = {vp=2, isHero=true, cost=6,},
        ["DA Dum Dum Dugan"] = {vp=1, isHero=true, isDefense=true, cost=2, id=5074},
        ["RC Agent Culson"] = {vp=1, isHero=true, isBribe=true, cost=2,},
        ["R1 Blade"] = {vp=1, isHero=true, cost=4, id=4083},
        ["CO2 Angela"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9549},
        ["MS Jane Foster"] = {vp=1, isHero=true, cost=4,},
        ["MS Scarlet Witch"] = {vp=2, isHero=true, cost=7,},
        ["MS Wiccan"] = {vp=1, isHero=true, cost=4,},
        ["MS Madame Web"] = {vp=1, isHero=true, cost=3,},
        ["MS Dazzler"] = {vp=1, isHero=true, cost=3,},
        ["MS Dr. Donald Blake"] = {vp=1, isHero=true, cost=2,},
        ["MS Wolfsbane"] = {vp=1, isHero=true, isDefense=true, cost=2,},

--Locations
        ["TU90 Yancy Street"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4247},
        ["CW Muir Island"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4403},
        ["CO9 Latveria"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["RC The Raft"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["R5 Daily Bugle"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
        ["MARVEL Avenger's Mansion"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=1617},
        ["TV Madripoor"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["MARVEL Ravencroft Institute"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7037},
        ["DA Baxter Building"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=6434},
        ["R5 Sanctum Sanctorium"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
        ["R2 Midtown High School"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7408},
        ["TU The Concaverse"] = {vp=1, isLocation=true, isAttack=true, isOngoing=true, cost=5, id=8132},
        ["TU90 New York City"] = {vp=1, isLocation=true, isOngoing=true, cost=3, id=6643},
        ["IW1 Brimstone Dimension"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5570},
        ["RC Savage Land"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["CO1 Wakanda"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=1030},
        ["R3 Worldship"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
        ["CO2 The Peak"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=6086},
        ["IW5 Olympus"] = {vp=2, isLocation=true, isOngoing=true, cost=7,},
        ["MARVEL Brooklyn Bridge"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=8226},
        ["KIB Bar With No Name"] = {vp=1, isLocation=true, isDefense=true, isOngoing=true, cost=5, id=7085},
        ["R1 Tony Stark's Workshop"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5817},
        ["TV Genosha"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["R5 Hydra Flying Island"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["CO3 Negative Zone"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=6972},
        ["R3 S.H.I.E.L.D. Helicarrier"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
        ["MARVEL Danger Room"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=5956},
        ["R2 Asteroid M"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=5400},
        ["MV Xavier Institute"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=4537},
        ["RC Oscorp Industries"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["C1 Hell's Kitchen"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4657},
        ["TU Monster Isle"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=3123},
        ["MARVEL The Blue Area of the Moon"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=9435},
        ["IW2 Atlantis"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=7099},
