--Heroes
        ["CW Moon Knight"] = {vp=1, isHero=true, cost=3, id=7178},
        ["R4 Armor"] = {vp=2, isHero=true, isDefense=true, cost=5,},
        ["RC Night Thrasher"] = {vp=1, isHero=true, cost=5,},
        ["R4 Freyja"] = {vp=2, isHero=true, isBlock=true, blockValue=3, cost=5,},
        ["IW Northstar"] = {vp=1, isHero=true, isOngoing=true, cost=4, id=1791},
        ["RC Jessica Jones"] = {vp=1, isHero=true, isBribe=true, cost=3,},
        ["RC Iron Patriot"] = {vp=2, isHero=true, cost=6,},
        ["CW Cosmo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5000},
        ["R5 Cosmo"] = {vp=1, isHero=true, cost=4,},
        ["RC Linda Carter"] = {vp=1, isHero=true, cost=4,},
        ["CW2 Black Widdow"] = {vp=1, isHero=true, isAttack=true, cost=3,},
        ["IW5 Jeff"] = {vp=2, isHero=true, isDefense=true, cost=7,},
        ["CO11 Daredevil"] = {vp=1, isHero=true, cost=5,},
        ["SW Namor"] = {vp=1, isHero=true, cost=3, id=1049},
        ["CO11 Hawkeye"] = {vp=2, isHero=true, cost=4,},
        ["IW5 Adam Warlock"] = {vp=3, isHero=true, isDefense=true, cost=8,},
        ["RC Devil DInossaur"] = {vp=1, isHero=true, isDefense=true, cost=3,},
        ["TV Valkyrie"] = {vp=1, isHero=true, cost=4, isOngoing=true, isBribe=true,},
        ["CW Triton"] = {vp=1, isHero=true, cost=3, id=6213},
        ["TV The Thing"] = {vp=2, isHero=true, cost=6, isBribe=true,},
        ["R4 Howard the Duck"] = {vp=1, isHero=true, isDefense=true, cost=4,},
        

--Locations
        ["TU90 Yancy Street"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4247},
        ["CW Muir Island"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4403},
        ["CO9 Latveria"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["RC The Raft"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["R5 Daily Bugle"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
        ["MARVEL Avenger's Mansion"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=1617},
        ["TV Madripoor"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["MARVEL Ravencroft Institute"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7037},
        ["DA Baxter Building"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=6434},
        ["R5 Sanctum Sanctorium"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
        ["R2 Midtown High School"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7408},
        ["TU The Concaverse"] = {vp=1, isLocation=true, isAttack=true, isOngoing=true, cost=5, id=8132},
        ["TU90 New York City"] = {vp=1, isLocation=true, isOngoing=true, cost=3, id=6643},
        ["IW1 Brimstone Dimension"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5570},
        ["RC Savage Land"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["CO1 Wakanda"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=1030},
        ["R3 Worldship"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
        ["CO2 The Peak"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=6086},
        ["IW5 Olympus"] = {vp=2, isLocation=true, isOngoing=true, cost=7,},
        ["MARVEL Brooklyn Bridge"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=8226},
        ["KIB Bar With No Name"] = {vp=1, isLocation=true, isDefense=true, isOngoing=true, cost=5, id=7085},
        ["R1 Tony Stark's Workshop"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5817},
        ["TV Genosha"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["R5 Hydra Flying Island"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
        ["CO3 Negative Zone"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=6972},
        ["R3 S.H.I.E.L.D. Helicarrier"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
        ["MARVEL Danger Room"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=5956},
        ["R2 Asteroid M"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=5400},
        ["MV Xavier Institute"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=4537},
        ["RC Oscorp Industries"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
        ["C1 Hell's Kitchen"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4657},
        ["TU Monster Isle"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=3123},
        ["MARVEL The Blue Area of the Moon"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=9435},
        ["IW2 Atlantis"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=7099},
