--Equipamento
    ["AA Joia da Mente"] = {vp=0, isEquipment=true, isExpPowerRing=true, isAttack=true, cost=5, id=7910},
    ["AA A Joia do Poder"] = {vp=0, isEquipment=true, isExpPowerRing=true, isDefense=true, cost=5, id=5382},
    ["R2 A Joia do Poder"] = {vp=1, isEquipment=true, isPowerRing=true, isDefense=true, cost=5, id=6406},
    ["IW5 A Manopla do Infinito"] = {vp=3, isEquipment=true, isPowerRing=true, cost=8,},
    ["MARVEL A Joia da Alma"] = {vp=1, isEquipment=true, isPowerRing=true, cost=3, id=1737},
    ["CW2 A Joia do Poder"] = {vp=2, isEquipment=true, isPowerRing=true, cost=6,},
    ["IW2 A Joia da Alma"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=7525},
    ["AA A Joia do Espaço"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=7121},
    ["AA A Joia da Realidade"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=9741},
    ["AA A Joia do Espaço"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=8012},
    ["IW2 A Joia do Tempo"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=9986},
    ["CW2 A Joia da Mente"] = {vp=2, isEquipment=true, isPowerRing=true, cost=6,},
    ["R2 A Joia da Mente"] = {vp=1, isEquipment=true, isPowerRing=true, isAttack=true, cost=4, id=7365},
    ["CO12 Santuário II"] = {vp=1, isEquipment=true, cost=4,},
    ["CO11 Espada de Ébano"] = {vp=2, isEquipment=true, cost=6,},
    ["MARVEL Tridente de Netuno"] = {vp=1, isEquipment=true, cost=3, id=8914},
    ["R5 Cérebro"] = {vp=2, isEquipment=true, cost=7,},
    ["RC Cetro de Controle Cósmico"] = {vp=2, isEquipment=true, cost=6,},
    ["SW Escudo do Treinador"] = {vp=2, isEquipment=true, isOngoing=true, cost=6, id=6668},
    ["R5 Sentinelas de Ultron"] = {vp=1, isEquipment=true, cost=3,},
    ["CO11 Pássaro Negro"] = {vp=2, isEquipment=true, cost=4,},
    ["KIB All-Black A Necroespada"] = {vp=1, isEquipment=true, isMetal=true, cost=3, id=9801},
    ["CO9 Martelo Universal"] = {vp=1, isEquipment=true, isDefense=true, cost=4,},
    ["MARVEL Garras de Adamantium"] = {vp=1, isEquipment=true, cost=3, id=1120},
    ["CO7 Cubo Cósmico"] = {vp=2, isEquipment=true, cost=7, id=5975},
    ["R4 Carro do Justiceiro"] = {vp=1, isEquipment=true, cost=3,},
    ["C1 Tentáculos do Doutor Octopus"] = {vp=1, isEquipment=true, cost=3, id=5736},
    ["CW Espada da Alma"] = {vp=1, isEquipment=true, cost=5, id=4105},
    ["TU90 Mochila a Jato"] = {vp=1, isEquipment=true, cost=4, id=7672},
    ["C2 Facas de Vibranium"] = {vp=1, isEquipment=true, cost=2, id=1087},
    ["RC Destruidor de Gelo"] = {vp=2, isEquipment=true, isAttack=true, cost=6,},
    ["CW2 Bug-Aranha"] = {vp=1, isEquipment=true, cost=2,},
    ["TU90 Blaster"] = {vp=1, isEquipment=true, cost=2, id=4355},
    ["CO5 Talária Sandálias Aladas"] = {vp=0, isEquipment=true, cost=3, id=9518},
    ["CW2 Mjolnir"] = {vp=1, isEquipment=true, cost=4,},
    ["TU90 Rastreador-Aranha"] = {vp=1, isEquipment=true, cost=3, id=8155},
    ["CW2 Flecha Explosiva"] = {vp=1, isEquipment=true, isAttack=true, cost=4,},
    ["CW2 Adagas Sai"] = {vp=1, isEquipment=true, cost=3,},
    ["RC Excalibur"] = {vp=1, isEquipment=true, isDefense=true, cost=3,},
    ["R4 Armadura do Destruidor"] = {vp=2, isEquipment=true, isDefense=true, cost=7,},
    ["CO5 Ferrão da Viúva"] = {vp=0, isEquipment=true, cost=3, id=9705},
    ["KIB Vírus Legado"] = {vp=1, isEquipment=true, isMetal=true, cost=4, id=8045},
    ["IW2 Armadura de Adamantium"] = {vp=4, isEquipment=true, isMetal=true, isDefense=true, cost=9, id=6085},
    ["KIB K-44"] = {vp=1, isEquipment=true, isMetal=true, cost=2, id=6081},
    ["TU90 Bea e Arthur"] = {vp=1, isEquipment=true, cost=2, id=1253},
    ["MS Capa da Levitação"] = {vp=2, isEquipment=true, cost=7},
    ["R5 Exército de Sentinelas"] = {vp=2, isEquipment=true, cost=5,},
    ["CO12 Arma Elemental"] = {vp=1, isEquipment=true, isDefense=true, cost=5,},
    ["IW4 Mapa Holográfico"] = {vp=1, isEquipment=true, isOngoing=true, cost=4, id=3112},
    ["R3 Portal Temporal"] = {vp=3, isEquipment=true, cost=7,},
    ["RC Moto-Aranha"] = {vp=1, isEquipment=true, cost=4,},
    ["IW3 Portão Eterno"] = {vp=1, isEquipment=true, isDefense=true, cost=4, id=5317},
    ["TU90 Pernas Expansíveis"] = {vp=1, isEquipment=true, cost=1, id=6753},
    ["TU Milano"] = {vp=2, isEquipment=true, isDefense=true, cost=7, id=8729},
    ["R1 Bug-Aranha"] = {vp=1, isEquipment=true, cost=3, id=9093},
    ["CW Cetro de Loki"] = {vp=1, isEquipment=true, isAttack=true, cost=4, id=4960},
    


--Super Poder
    ["TU90-2 Divindade Elemental"] = {vp=1, isSuperPower=true, cost=2,},
    ["RC Força Bruta"] = {vp=2, isSuperPower=true, isBribe=true, cost=6,},
    ["SW3 Supremacia Arcana"] = {vp=1, isSuperPower=true, cost=5,},
    ["RC Pancada Sísmica"] = {vp=1, isSuperPower=true, isBribe=true, cost=3,},
    ["RC Fortuna Felina"] = {vp=1, isSuperPower=true, cost=4,},
    ["RC Salve Hydra!"] = {vp=3, isSuperPower=true, isBribe=true, cost=7,},
    ["CO11 Cartas Explosivas"] = {vp=2, isSuperPower=true, cost=3,},
    ["TV Ira do Titã"] = {vp=1, isSuperPower=true, cost=5, isAttack=true,},
    ["R5 Sentidos Apurados"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW4 Avante Vingadores!"] = {vp=1, isSuperPower=true, isOngoing=true, cost=5, id=7223},
    ["SW Raio Cósmico"] = {vp=1, isSuperPower=true, cost=5, id=3498},
    ["TU Crescimento Desenfreado"] = {vp=2, isSuperPower=true, isOngoing=true, cost=6, id=6409},
    ["KIB Revelação Arcana"] = {vp=1, isSuperPower=true, cost=4, id=2703},
    ["R3 Batalhão de Neve"] = {vp=1, isSuperPower=true, cost=3,},
    ["R5 Aliança Perigosa"] = {vp=1, isSuperPower=true, cost=2,},
    ["CW Absorção de Choque"] = {vp=1, isSuperPower=true, cost=4, id=8968},
    ["R4 União Mutante"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW5 Abraço Parasita"] = {vp=2, isSuperPower=true, cost=5,},
    ["CC1 Ressurreição"] = {vp=1, isSuperPower=true, cost=5,},
    ["R5 Arsenal Orgânico"] = {vp=1, isSuperPower=true, cost=4,},
    ["CW2 Grito Hipersônico"] = {vp=2, isSuperPower=true, isAttack=true, cost=5,},
    ["MS Escudo dos Serafins"] = {vp=1, isSuperPower=true, isDefense=true, isOngoing=true, cost=5,},
    ["MARVEL Rajada Óptica"] = {vp=2, isSuperPower=true, cost=6, id=9007},
    ["CO3 Potencial Ilimitado"] = {vp=1, isSuperPower=true, cost=4, id=8431},
    ["DA Unibeam"] = {vp=1, isSuperPower=true, cost=4, id=5429},
    ["CO12 Insanidade"] = {vp=1, isSuperPower=true, cost=4,},
    ["R5 Plano Mestre"] = {vp=1, isSuperPower=true, cost=4,},
    ["R1 Vigília Urbana"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=1709},
    ["CO11 Fumaça Espiritual"] = {vp=1, isSuperPower=true, cost=3,},
    ["CO5 Em Chamas!"] = {vp=0, isSuperPower=true, cost=5, id=9446},
    ["MS Fúria Espelhada"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW2 Campo de força Invisível"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=5857},
    ["CO11 Impacto Brutal"] = {vp=1, isSuperPower=true, cost=4,},
    ["IW5 Força Fênix"] = {vp=3, isSuperPower=true, cost=8,},
    ["TU Agilidade Acrobática"] = {vp=1, isSuperPower=true, isDefense=true, cost=1, id=6956},
    ["R4 Feixe de Neutralização"] = {vp=1, isSuperPower=true, cost=4,},
    ["TU Eletrocinese"] = {vp=1, isSuperPower=true, isAttack=true, cost=4, id=7492},
    ["R4 Força Olímpica"] = {vp=1, isSuperPower=true, cost=4,},
    ["R2 Adaga Psíquica"] = {vp=1, isSuperPower=true, cost=5, id=8463},
    ["AA Invisibilidade"] = {vp=1, isSuperPower=true, isDefense=true, isOngoing=true, cost=3, id=1757},
    ["MS Forma Astral"] = {vp=2, isSuperPower=true, isDefense=true, cost=6},
    ["RC Hospedeiro Instável"] = {vp=1, isSuperPower=true, isBribe=true, cost=5,},
    ["R4 Ofensiva Brutal"] = {vp=1, isSuperPower=true, cost=2,},
    ["AA Domínio Molecular"] = {vp=2, isSuperPower=true, cost=7, id=8004},
    ["R4 Velocidade Cósmica"] = {vp=2, isSuperPower=true, cost=7,},
    ["TU Absorção de Poderes"] = {vp=1, isSuperPower=true, cost=4, id=7566},
    ["R5 Arremesso Especial"] = {vp=2, isSuperPower=true, cost=7,},
    ["AA Solo Sagrado"] = {vp=1, isSuperPower=true, cost=3, id=9273},
    ["R1 Ódio Primal"] = {vp=1, isSuperPower=true, cost=3, id=4867},
    ["CO5 Força em Números"] = {vp=0, isSuperPower=true, cost=5, id=7929},
    ["CO6 Fator de Cura"] = {vp=1, isSuperPower=true, cost=5, id=6212},
    ["IW3 Prisão Ártica"] = {vp=1, isSuperPower=true, cost=6, id=9305},
    ["CW2 Golpe de Misericórdia"] = {vp=1, isSuperPower=true, cost=2,},
    ["CW2 Agilidade Sensorial"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["TU90 Arrancada Imprudente"] = {vp=1, isSuperPower=true, cost=5, id=7275},
    ["RC Controle Absoluto"] = {vp=1, isSuperPower=true, cost=5,},
    ["RC Tudo ou Nada"] = {vp=1, isSuperPower=true, isBribe=true, cost=2,},
    ["CO10 Ruptura Temporal"] = {vp=0, isSuperPower=true, isTimeLineUp=true, cost=6,},
    ["MARVEL Telecinésia"] = {vp=1, isSuperPower=true, cost=3, id=1785},
    ["CW Manipulação do Vazio"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=9799},
    ["CW Fúria Peluda"] = {vp=1, isSuperPower=true, cost=3, id=1856},
    ["CW2 ESMAGA!"] = {vp=2, isSuperPower=true, cost=6,},
    ["RC Engenharia Calculada"] = {vp=1, isSuperPower=true, cost=3,},
    ["CW2 Rajadas Fotônicas"] = {vp=1, isSuperPower=true, cost=3,},
    ["R3 Domínio dos Ventos"] = {vp=2, isSuperPower=true, cost=5,},
    ["CO3 Campos Magnéticos"] = {vp=2, isSuperPower=true, cost=6, id=2002},
    ["TU90-2 Proteção Versátil"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["IW1 Magia do Caos"] = {vp=1, isSuperPower=true, cost=5, id=7327},
    ["TV Trabalho Sujo"] = {vp=1, isSuperPower=true, cost=4, isBribe=true,},
    ["R2 Arsenal Psiônico"] = {vp=1, isSuperPower=true, cost=2, id=6664},
    ["CW Relâmpago"] = {vp=1, isSuperPower=true, isAttack=true, cost=5, id=4550},
    ["MARVEL À Prova de Balas"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=4830},
    ["CW2 Tá na Hora do Pau!"] = {vp=1, isSuperPower=true, cost=5,},
    ["TU90 Elo Mental"] = {vp=1, isSuperPower=true, cost=2, id=2049},
    ["R2 Magnetismo"] = {vp=2, isSuperPower=true, cost=6, id=8379},
    ["R3 Teste de Resistência"] = {vp=1, isSuperPower=true,isAttack=true, cost=5,},
    ["R2 Armadura Psiônica"] = {vp=1, isSuperPower=true, isDefense=true, cost=5, id=7210},
    ["SW Aço Orgânico"] = {vp=2, isSuperPower=true, isDefense=true, cost=5, id=2145},
    ["KIB Sentido Aranha"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=5607},
    ["R4 Investida Final"] = {vp=2, isSuperPower=true, cost=6,},
    ["RC Legado de Loucura"] = {vp=1, isSuperPower=true, isBribe=true, cost=3,},
    ["IW1 Deslizamento Glacial"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=5262},
    ["R1 Barreira Quântica"] = {vp=2, isSuperPower=true, isDefense=true, cost=6, id=9494},
    ["MS Ponto de Equilibrio"] = {vp=1, isSuperPower=true, cost=3,},
    ["MS Influência Sinistra"] = {vp=1, isSuperPower=true, isAttack=true, cost=3,},
    ["MS Ponto de Ignição"] = {vp=2, isSuperPower=true, isAttack=true, cost=6,},
    ["MS Evolução Forçada"] = {vp=1, isSuperPower=true, cost=2,},
    ["MS Resistência Heroica"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["SW Essência do Trapaceiro"] = {vp=2, isSuperPower=true, cost=6, id=1268},
    ["R3 Investida do Ferrão"] = {vp=2, isSuperPower=true, cost=5,},
    ["TU90 Super Força"] = {vp=2, isSuperPower=true, cost=5, id=3857},
    ["DA Raios Repulsores"] = {vp=1, isSuperPower=true, cost=3, id=2104},
    ["CO10 Onipresença"] = {vp=-3, isSuperPower=true, isOngoing=true, isTimeLineUp=true, cost=6,},
    ["RC Controle Mental"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["TU BAMF!"] = {vp=1, isSuperPower=true, isOngoing=true, cost=3, id=4488},
    ["RC Sorte Garantida"] = {vp=1, isSuperPower=true, cost=4,},
    ["CO1 Sobrecarga de Chi"] = {vp=2, isSuperPower=true, cost=6, id=6766},
    ["AA Manipulação da Realidade"] = {vp=1, isSuperPower=true, cost=7, id=5847},

--Villains
    ["AA Attuma"] = {vp=1, isVillain=true, cost=2, id=1336},
    ["R5 Soprano"] = {vp=1, isVillain=true, cost=3,},
    ["R1 Venom"] = {vp=1, isVillain=true, cost=4, id=4124},
    ["TU M.O.D.O.K."] = {vp=1, isVillain=true, cost=2, id=4500},
    ["CO9 Alto Evolucionário"] = {vp=2, isVillain=true, isDefense=true, cost=6,},
    ["R4 Blob"] = {vp=1, isVillain=true, cost=3,},
    ["R5 Crânio Ardente"] = {vp=1, isVillain=true, cost=3,},
    ["IW5 Carnificina Lobisomem"] = {vp=3, isVillain=true, cost=6,},
    ["R5 Próxima Meia-Noite"] = {vp=1, isVillain=true, cost=3,},
    ["RC Shriek"] = {vp=1, isVillain=true, isDefense=true, cost=5,},
    ["TU Monge do Ódio"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=9000},
    ["CO11 Víbora"] = {vp=1, isVillain=true, cost=5,},
    ["CC1 Escorpião"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
    ["R2 Blastaar"] = {vp=2, isVillain=true, isDefense=true, cost=6, id=4743},
    ["KIB Arcanjo"] = {vp=2, isVillain=true, isMetal=true, isAttack=true, cost=7, id=3061},
    ["CC1 Jaqueta Amarela"] = {vp=1, isVillain=true, isAttack=true, cost=4,},
    ["Marvel Thunderbolts"] = {vp=0, isVillain=true, cost=4, id=9516},
    ["R4 Mamba Negra"] = {vp=2, isVillain=true, cost=4,},
    ["R5 Abutre"] = {vp=1, isVillain=true, cost=2,},
    ["RC Venom"] = {vp=2, isVillain=true, cost=7,},
    ["TV O Consertador"] = {vp=1, isVillain=true, cost=2, isOngoing=true, isBribe=true,},
    ["R5 Homem-Impossível"] = {vp=2, isVillain=true, cost=6,},
    ["RC Rattus"] = {vp=1, isVillain=true, isBribe=true, cost=2,},
    ["R5 Hulk Contra o Mundo"] = {vp=1, isVillain=true, cost=5,},
    ["IW5 Duende Macabro"] = {vp=0, isVillain=true, cost=5,},
    ["CW Coração Negro"] = {vp=1, isVillain=true, cost=3, id=3500},
    ["CO7 O Caído"] = {vp=1, isVillain=true, cost=5, id=7900},
    ["CW2 Homem-Aranha Simbionte"] = {vp=1, isVillain=true, isDefense=true, cost=2,},
    ["CW Titânia"] = {vp=1, isVillain=true, isDefense=true, cost=3, id=5897},
    ["MARVEL Retalho"] = {vp=1, isVillain=true, cost=2, id=1319},
    ["TU Kang"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=1316},
    ["CO11 Carnificina"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
    ["CO9 Elektra"] = {vp=1, isVillain=true, isAttack=true, cost=3,},
    ["KIB Magneto"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=2013},
    ["R3 Mercúrio Zumbi"] = {vp=3, isVillain=true, isAttack=true, cost=7,},
    ["TU Nebula"] = {vp=1, isVillain=true, isOngoing=true, cost=4, id=9940},
    ["DA Supergigante"] = {vp=1, isVillain=true, cost=3, id=4630},
    ["RC Pensador Louco"] = {vp=1, isVillain=true, isBribe=true, cost=4,},
    ["TU Rino"] = {vp=1, isVillain=true, cost=3, id=4158},
    ["IW2 Namor Zumbi"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=9302},
    ["TU90 Pets dos Mestres do Mal"] = {vp=1, isVillain=true, cost=2, id=8228},
    ["TV Muse"] = {vp=1, isVillain=true, cost=3, isBribe=true,},
    ["RC Gatuno"] = {vp=1, isVillain=true, isBribe=true, cost=3,},
    ["RC Pyro"] = {vp=1, isVillain=true, isAttack=true, isBribe=true, cost=4,},
    ["CO2 Blade"] = {vp=1, isVillain=true, cost=5, id=6557},
    ["CO9 Víbora"] = {vp=2, isVillain=true, isAttack=true, cost=5,},
    ["CO11 Elektra"] = {vp=1, isVillain=true, cost=4,},
    ["IW5 Esquecimento"] = {vp=3, isVillain=true, cost=6,},
    ["TU Wendigo"] = {vp=1, isVillain=true, isDefense=true, cost=5, id=6650},
    ["KIB Monstro-Aranha"] = {vp=2, isVillain=true, cost=2, id=8624},
    ["CW Abominável"] = {vp=1, isVillain=true, cost=5, id=4747},
    ["R4 Pestilência"] = {vp=2, isVillain=true, isAttack=true, isConfrontation=true, cost=6,},
    ["R2 Ego, o Planeta Vivo"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=4516},
    ["RC Fanático"] = {vp=1, isVillain=true, isDefense=true, cost=4,},
    ["RC Sapo"] = {vp=1, isVillain=true, isBribe=true, cost=5,},
    ["TV Caveira Vermelha"] = {vp=2, isVillain=true, cost=5, isAttack=true,},
    ["TU Homem-Toupeira"] = {vp=1, isVillain=true, isDefense=true, isOngoing=true, cost=2, id=5859},
    ["CO5 Magma"] = {vp=0, isVillain=true, cost=3, id=5922},
    ["TU902 Homem-Fuleiro"] = {vp=1, isVillain=true, cost=5,},
    ["IW5 Homem  de Ferro Sentinela"] = {vp=3, isVillain=true, cost=5,},
    ["TU Cassandra Nova"] = {vp=2, isVillain=true, isAttack=true, cost=6, id=4075},
    ["MARVEL Venom"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=5050},
    ["MS Gabriel Housman"] = {vp=1, isVillain=true, cost=4,},
    ["IW5 Lady Letal"] = {vp=2, isVillain=true, cost=4,},
    ["IW5 Homem de Ferro Cancerverso"] = {vp=3, isVillain=true, cost=6,},
    ["TU Homem Radioativo"] = {vp=1, isVillain=true, cost=3, id=6799},
    ["CW2 Agente Venom"] = {vp=1, isVillain=true, cost=3,},
    ["R5 Cynthia Von Doom"] = {vp=1, isVillain=true, cost=4,},
    ["IW1 Emma Frost"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=3920},
    ["RC Besouro"] = {vp=1, isVillain=true, cost=3,},
    ["DA Líder"] = {vp=1, isVillain=true, cost=2, id=4899},
    ["RC Capitão Louco"] = {vp=2, isVillain=true, cost=6,},
    ["R3 Laser Vivo"] = {vp=2, isVillain=true, cost=6,},
    ["CW Magneto"] = {vp=1, isVillain=true, cost=3, id=6914},
    ["R5 Electro"] = {vp=1, isVillain=true, cost=4,},
    ["R1 Muse"] = {vp=1, isVillain=true, cost=2, id=7511},
    ["RC Morbius"] = {vp=1, isVillain=true, cost=4,},
    ["R5 Hulk Cinza Sr. Tira-teima"] = {vp=2, isVillain=true, cost=5,},
    ["CW Orka"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=4838},
    ["R5 Abominável"] = {vp=2, isVillain=true, cost=7,},
    ["TV Manto e Adaga"] = {vp=1, isVillain=true, cost=4, isOngoing=true, isBribe=true,},
    ["CO11 Lagarto"] = {vp=1, isVillain=true, isDefense=true, cost=3,},
    ["RC Mestre dos Bonecos"] = {vp=1, isVillain=true, cost=2,},
    ["IW4 O Capuz"] = {vp=1, isVillain=true, isOngoing=true, cost=1, id=6259},
    ["R4 Mefisto"] = {vp=2, isVillain=true, isConfrontation=true, cost=5,},
    ["R5 Senhor Negativo"] = {vp=1, isVillain=true, cost=3,},
    ["CW A Ninhada"] = {vp=1, isVillain=true, cost=2, id=3899},
    ["R2 Shocker"] = {vp=1, isVillain=true, cost=3, id=5482},
    ["R3 Vulcan"] = {vp=0, isVillain=true, cost=3,},
    ["R1 Mary Tifoide"] = {vp=1, isVillain=true, cost=5, id=5622},
    ["RC Cabeça de Martelo"] = {vp=0, isVillain=true, isExpBribe=true, cost=7,},
    ["MARVEL Dentes de Sabre"] = {vp=2, isVillain=true, cost=7, id=5005},
    ["MARVEL Legião"] = {vp=1, isVillain=true, cost=2, id=3447},
    ["AA Muse"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=7807},
    ["DA Gárgula Cinzento"] = {vp=1, isVillain=true, cost=4, id=7265},
    ["KIB Mercenário"] = {vp=1, isVillain=true, isMetal=true, isDefense=true, cost=4, id=9630},
    ["MS Alioth"] = {vp=2, isVillain=true, cost=6,},
    ["MS Fanático"] = {vp=1, isVillain=true, isDefense=true, cost=4,},
    ["MS Mímico"] = {vp=1, isVillain=true, cost=3,},


--Heróis
    ["CW Cavaleiro da Lua"] = {vp=1, isHero=true, cost=3, id=7178},
    ["R4 Armadura"] = {vp=2, isHero=true, isDefense=true, cost=5,},
    ["RC Radical"] = {vp=1, isHero=true, cost=5,},
    ["R4 Freyja"] = {vp=2, isHero=true, isBlock=true, blockValue=3, cost=5,},
    ["IW Estrela Polar"] = {vp=1, isHero=true, isOngoing=true, cost=4, id=1791},
    ["RC Jessica Jones"] = {vp=1, isHero=true, isBribe=true, cost=3,},
    ["RC Patriota de Ferro"] = {vp=2, isHero=true, cost=6,},
    ["CW Cosmo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5000},
    ["R5 Cosmo"] = {vp=1, isHero=true, cost=4,},
    ["RC Linda Carter"] = {vp=1, isHero=true, cost=4,},
    ["CW2 Viúva Negra"] = {vp=1, isHero=true, isAttack=true, cost=3,},
    ["IW5 Jeff"] = {vp=2, isHero=true, isDefense=true, cost=7,},
    ["CO11 Demolidor"] = {vp=1, isHero=true, cost=5,},
    ["SW Namor"] = {vp=1, isHero=true, cost=3, id=1049},
    ["CO11 Gavião Arqueiro"] = {vp=2, isHero=true, cost=4,},
    ["IW5 Adam Warlock"] = {vp=3, isHero=true, isDefense=true, cost=8,},
    ["RC Dinossauro Diabólico"] = {vp=1, isHero=true, isDefense=true, cost=3,},
    ["TV Valquíria"] = {vp=1, isHero=true, cost=4, isOngoing=true, isBribe=true,},
    ["CW Tritão"] = {vp=1, isHero=true, cost=3, id=6213},
    ["TV A Coisa"] = {vp=2, isHero=true, cost=6, isBribe=true,},
    ["R4 Howard o Pato"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["TV Goose"] = {vp=1, isHero=true, cost=5, isOngoing=true, isDefense=true,},
    ["IW5 Youndu"] = {vp=2, isHero=true, cost=5,},
    ["R3 Seda"] = {vp=1, isHero=true, cost=4,},
    ["IW2 Capitão Mar-Vell"] = {vp=1, isHero=true, cost=4, id=6613},
    ["R3 Homem de Gelo"] = {vp=1, isHero=true, isAttack=true, cost=4,},
    ["CO9 Falcão"] = {vp=1, isHero=true, isAttack=true, cost=4,},
    ["RC Felina"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=5,},
    ["AS Adam Warlock"] = {vp=2, isHero=true, cost=7, id=7644},
    ["CO10 Namora Terra X"] = {vp=-2, isHero=true, isDefense=true, isTimeLineUp=true, cost=6,},
    ["MS Dr. Michael Morbius"] = {vp=1, isHero=true, cost=4,},
    ["TU Drax"] = {vp=1, isHero=true, cost=4, id=7267},
    ["RC Mancha Solar"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["R1 Miles Morales"] = {vp=1, isHero=true, cost=4, id=5295},
    ["CW Filhos da Meia-Noite"] = {vp=1, isHero=true, isDefense=true, cost=3, id=6352},
    ["RC Misty Knight"] = {vp=2, isHero=true, cost=6,},
    ["SW2 Thor Jane Foster"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["SW Eve Bakian nova corp."] = {vp=1, isHero=true, cost=4, id=1285},
    ["TV Motoqueiro Fantasma"] = {vp=1, isHero=true, cost=3, isBribe=true,},
    ["R5 Coração de Ferro"] = {vp=2, isHero=true, cost=5,},
    ["KIB Sr. Fantástico"] = {vp=1, isHero=true, cost=3, id=6084},
    ["MARVEL Deadpool"] = {vp=1, isHero=true, cost=3, id=6872},
    ["DA Coração de Ferro"] = {vp=1, isHero=true, cost=3, id=8620},
    ["DA Onda"] = {vp=1, isHero=true, cost=2, id=1728},
    ["CO11 Radical"] = {vp=1, isHero=true, cost=4,},
    ["CO1 Punho de Ferro"] = {vp=1, isHero=true, cost=4, id=6666},
    ["IW4 Blink"] = {vp=2, isHero=true, isOngoing=true, cost=6, id=8216},
    ["SW Deadpool"] = {vp=0, isCharacter=true, id=7597},
    ["TU Solaris"] = {vp=1, isHero=true, cost=2, id=9694},
    ["R5 Ciclope"] = {vp=2, isHero=true, cost=6,},
    ["IW5 Domino"] = {vp=2, isHero=true, cost=5,},
    ["DA Maria Hill"] = {vp=1, isHero=true, cost=4, id=8153},
    ["R5 Trish Tilby"] = {vp=1, isHero=true, cost=2,},
    ["RC Cavaleiro da Lua"] = {vp=1, isHero=true, cost=4,},
    ["R3 Míssil"] = {vp=1, isHero=true, cost=3,},
    ["AA Gwen-Aranha"] = {vp=1, isHero=true, cost=3, id=9385},
    ["R5 Ciclope"] = {vp=1, isHero=true, cost=5,},
    ["R4 Falcão"] = {vp=1, isHero=true, isDefense=true, cost=5,},
    ["RC Guarda da Prisão"] = {vp=1, isHero=true, isBribe=true, cost=1,},
    ["CO1 Garota Esquilo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5755},
    ["RC América Chavez"] = {vp=2, isHero=true, isBribe=true, cost=7,},
    ["AA Psylocke"] = {vp=1, isHero=true, isDefense=true, cost=2, id=6046},
    ["R4 Hércules"] = {vp=1, isHero=true, isConfrontation=true, cost=5,},
    ["CO10 Capitão Britânia Terra X"] = {vp=-2, isHero=true, isTimeLineUp=true, cost=5,},
    ["R2 O Vigia"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7874},
    ["TU Namorita"] = {vp=1, isHero=true, isOngoing=true, cost=3, id=4487},
    ["IW4 Valquíria"] = {vp=2, isHero=true, isDefense=true, cost=6, id=9723},
    ["TU Homem-Múltiplo"] = {vp=1, isHero=true, cost=2, id=1767},
    ["CW Havok"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9933},
    ["TU90 Ciclope"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7161},
    ["RC Happy Hogan"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=3,},
    ["AA Jean Grey"] = {vp=1, isHero=true, cost=3, id=8883},
    ["IW1 Wolverine"] = {vp=1, isHero=true, cost=5, id=8902},
    ["CW Irmão Voodoo"] = {vp=1, isHero=true, cost=3, id=6429},
    ["R5 Betty Ross"] = {vp=1, isHero=true, cost=2,},
    ["R5 Mulher-Hulk"] = {vp=2, isHero=true, cost=7,},
    ["CO11 Visão"] = {vp=2, isHero=true, cost=6,},
    ["TU 90-2 Doop"] = {vp=1, isHero=true, cost=4,},
    ["IW5 Jean Grey"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["CO3 Quasar"] = {vp=1, isHero=true, cost=5, id=6299},
    ["SW3 Wolverine"] = {vp=1, isHero=true, cost=5,},
    ["CO11 Homem-Aranha"] = {vp=1, isHero=true, cost=3,},
    ["CC1 Poeira"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["IW5 Ciclone"] = {vp=2, isHero=true, cost=7,},
    ["CO12 Micro"] = {vp=1, isHero=true, cost=2,},
    ["TU Marvel Azul"] = {vp=1, isHero=true, isDefense=true, cost=4, id=5808},
    ["R4 Polaris"] = {vp=1, isHero=true, isBlock=true, blockValue=2, cost=4,},
    ["DA Rachel Summers"] = {vp=1, isHero=true, isDefense=true, cost=4, id=8676},
    ["R3 Célere"] = {vp=2, isHero=true, cost=5,},
    ["RC Symbie"] = {vp=1, isHero=true, cost=2,},
    ["CO11 Tocha Humana"] = {vp=2, isHero=true, cost=5,},
    ["R1 Máquina de Combate"] = {vp=1, isHero=true, cost=3, id=7521},
    ["CW2 Demolidor"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["R5 Mary Jane"] = {vp=1, isHero=true, cost=4,},
    ["R2 Phyla-Vell"] = {vp=1, isHero=true, cost=3, id=5209},
    ["R5 Vampira"] = {vp=2, isHero=true, cost=6,},
    ["DA Dum Dum Dugan"] = {vp=1, isHero=true, isDefense=true, cost=2, id=5074},
    ["RC Agente Culson"] = {vp=1, isHero=true, isBribe=true, cost=2,},
    ["R1 Blade"] = {vp=1, isHero=true, cost=4, id=4083},
    ["CO2 Angela"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9549},
    ["MS Jane Foster"] = {vp=1, isHero=true, cost=4,},
    ["MS Feiticeira Escarlate"] = {vp=2, isHero=true, cost=7,},
    ["MS Wiccano"] = {vp=1, isHero=true, cost=4,},
    ["MS Madame Teia"] = {vp=1, isHero=true, cost=3,},
    ["MS Cristal"] = {vp=1, isHero=true, cost=3,},
    ["MS Dr. Donald Blake"] = {vp=1, isHero=true, cost=2,},
    ["MS Lupina"] = {vp=1, isHero=true, isDefense=true, cost=2,},
    
--Localizações
    ["TU90 Rua Yancy"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4247},
    ["CW Ilha Muir"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4403},
    ["CO9 Latvéria"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["RC A Balsa"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["R5 Clarim Diário"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
    ["MARVEL Mansão dos Vingadores"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=1617},
    ["TV Madripoor"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["MARVEL Instituto Ravencroft"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7037},
    ["DA Edifício Baxter"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=6434},
    ["R5 Sanctum Sanctorium"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
    ["R2 Colégio Midtown"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7408},
    ["TU O Concaverso"] = {vp=1, isLocation=true, isAttack=true, isOngoing=true, cost=5,
    ["TU90 Cidade de Nova York"] = {vp=1, isLocation=true, isOngoing=true, cost=3, id=6643},
    ["IW1 Dimensão de Enxofre"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5570},
    ["RC Terra Selvagem"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["CO1 Wakanda"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=1030},
    ["R3 Nave-Mundo"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
    ["CO2 O Pico"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=6086},
    ["IW5 Olimpo"] = {vp=2, isLocation=true, isOngoing=true, cost=7,},
    ["MARVEL Ponte do Brooklyn"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=8226},
    ["KIB Bar Sem Nome"] = {vp=1, isLocation=true, isDefense=true, isOngoing=true, cost=5, id=7085},
    ["R1 Oficina do Tony Stark"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5817},
    ["TV Genosha"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["R5 Ilha Flutuante da Hydra"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["CO3 Zona Negativa"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=6972},
    ["R3 Porta-aviões da S.H.I.E.L.D."] = {vp=1, isLocation=true, isOngoing=true, cost=5},
    ["MARVEL Sala de Perigo"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=5956},
    ["R2 Asteróide M"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=5400},
    ["MV Instituto Xavier"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=4537},
    ["RC Indústrias Oscorp"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["C1 A Cozinha do Diabo"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4657},
    ["TU Ilha dos Monstros"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=3123},
    ["MARVEL A Área Azul da Lua"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=9435},
    ["IW2 Atlântida"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=7099},
    
