-- MC Tier 1
	["CW Feiticeira Escarlate (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=8093},
    ["IW1 Feiticeira Escarlate"] = {vp=0, isCharacter=true, id=3545},
    ["CW2 Carnificina"] = {vp=0, isCharacter=true,},
    ["CC1 Ciclone"] = {vp=0, isCharacter=true,},
    ["IW1 Mercúrio"] = {vp=0, isCharacter=true, id=8396},
    ["IW4 Tritão"] = {vp=0, isCharacter=true, id=1991},
    ["CW Hulk (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=5356},
    ["KIB Hulk"] = {vp=0, isCharacter=true, id=1825},
    ["IW1 Hulk"] = {vp=0, isCharacter=true, id=7639},
    ["IW4 Ciclope"] = {vp=0, isCharacter=true, id=5443},
    ["IW2 Capitão Mar-vell (Character)"] = {vp=0, isCharacter=true, id=5572},
    ["IW4 Tempestade"] = {vp=0, isCharacter=true, id=8656},
    ["MS Fanático"] = {vp=0, isCharacter=true,},
    ["CO4 Aero"] = {vp=0, isCharacter=true, id=6875},
    ["RC Mystério"] = {vp=0, isCharacter=true,},
    ["CO3 Mulher Invisível"] = {vp=0, isCharacter=true, id=6119},
    ["CO2 Harpia"] = {vp=0, isCharacter=true, id=8386},
    ["C1 Homem-Aranha"] = {vp=0, isCharacter=true, id=1559},
    ["C4 Noturno"] = {vp=0, isCharacter=true, id=8130},
    ["TV Mandarim"] = {vp=0, isCharacter=true,},
    ["C3 Víbora"] = {vp=0, isCharacter=true, id=4022},
    ["RC Víbora"] = {vp=0, isCharacter=true,},
    ["CC1 Vampira"] = {vp=0, isCharacter=true,},
    ["CO3 Kitty Pryde"] = {vp=0, isCharacter=true, id=3411},
    ["CO6 Miles Morales"] = {vp=0, isCharacter=true, id=6827},
    ["IW4 Blink"] = {vp=0, isCharacter=true, id=5034},
    ["CO4 Cable"] = {vp=0, isCharacter=true, id=8590},
    ["CC1 Charles Xavier Professor X"] = {vp=0, isCharacter=true,},
    ["IW1 Visão"] = {vp=0, isCharacter=true, id=8566},
    ["CO3 Raio Negro"] = {vp=0, isCharacter=true, id=9641},
    ["CW Doutor Destino (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=4725},
    ["CW Doutor Destino (Level 3)"] = {vp=0, isVillain=true, isCharacter=true, cost=15, id=7042},
    ["IW2 Nova Prime"] = {vp=0, isCharacter=true, id=1500},
    ["PROMO Cosmo"] = {vp=0, isCharacter=true,},
    ["PROMO Célere"] = {vp=0, isCharacter=true, id=1487},
    ["CO6 Psylocke"] = {vp=0, isCharacter=true, id=9790},
    ["CO2 Agente 13 Sharon Carter"] = {vp=0, isCharacter=true, id=1315},
    ["CO1 Ciclone"] = {vp=0, isCharacter=true, id=5596},
    ["CW2 Capitã Marvel - Earth 101"] = {vp=0, isCharacter=true,},
    ["CW2 Hulk Contra o Mundo (Character)"] = {vp=0, isCharacter=true,},
    ["CW2 Gavião Arqueiro"] = {vp=0, isCharacter=true,},
    ["CO6 Blade"] = {vp=0, isCharacter=true, id=8136},
    ["IW2 Anjo"] = {vp=0, isCharacter=true, id=5115},
    ["CO10 Mercúrio Terra X"] = {vp=0, isCharacter=true,},
    ["MS Doutor Estranho"] = {vp=0, isCharacter=true,},
    ["CW Agatha Harkness (Level 3)"] = {vp=0, isVillain=true, isCharacter=true, cost=15, id=2129},
    ["CO12 Gata Negra"] = {vp=0, isCharacter=true,},
    ["CO6 Gata Negra"] = {vp=0, isCharacter=true, id=4365},
    ["CO6 Viúva Negra"] = {vp=0, isCharacter=true, id=4237},
    ["R4 O Sentinela (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9,},
    ["CO6 Máquina de Combate"] = {vp=0, isCharacter=true, id=4274},
    ["KIB Homem de Ferro"] = {vp=0, isCharacter=true, id=5148},
    ["IW5 Homem de Ferro"] = {vp=0, isCharacter=true,},
    ["CO11 Homem de Ferro Superior"] = {vp=0, isCharacter=true,},
    ["CO11 Homem de Ferro Darkhold"] = {vp=0, isCharacter=true,},
    ["SW Namor (Character)"] = {vp=0, isCharacter=true, id=6860},
    ["IW5 Namor"] = {vp=0, isCharacter=true,},
    
-- MC Tier 2
    ["CW Feiticeira Escarlate (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=8752},
    ["SW3 Feiticeira Escarlate"] = {vp=0, isCharacter=true,},
    ["MS Feiticeira Escarlate (Character)"] = {vp=0, isCharacter=true,},
    ["CO9 Feiticeira Escarlate"] = {vp=0, isCharacter=true,},
    ["CW Capitã Marvel (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=1433},
    ["IW1 Capitã Marvel"] = {vp=0, isCharacter=true, id=3947},
    ["MARVEL Capitã Marvel"] = {vp=0, isCharacter=true, id=7168},
    ["IW5 Capitã Marvel"] = {vp=0, isCharacter=true,},
    ["IW4 Miss Marvel"] = {vp=0, isCharacter=true, id=4708},
    ["TU Miss Marvel"] = {vp=0, isCharacter=true, id=5997},
    ["CC1 Capitão América"] = {vp=0, isCharacter=true,},
    ["SW2 Shanna"] = {vp=0, isCharacter=true,},
    ["RC Retalho"] = {vp=0, isCharacter=true,},
    ["PROMO Rapaz de Ferro"] = {vp=0, isCharacter=true,},
    ["R1 Carnificina (Level 2)"] = {vp=6, isVillain=true, isCharacter=true, cost=12, id=5752},
    ["R1 Carnificina (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=7197},
    ["RC Carnificina"] = {vp=0, isCharacter=true,},
    ["R3 Mercúrio (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9,},
    ["KIB Mercúrio (Character)"] = {vp=0, isCharacter=true, id=8264},
    ["IW5 Mercúrio"] = {vp=0, isCharacter=true,},
    ["IW4 Mercúrio"] = {vp=0, isCharacter=true, id=7715},
    ["MARVEL Mercúrio"] = {vp=0, isCharacter=true, id=5652},
    ["R5 Hulk (Level 2)"] = {vp=6, isCharacter=true,},
    ["CW Hulk (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=7243},
    ["PROMO Mulher-Hulk"] = {vp=0, isCharacter=true,},
    ["IW5 Ciclope"] = {vp=0, isCharacter=true,},
    ["TU Ciclope"] = {vp=0, isCharacter=true, id=3495},
    ["CO1 Rachel Summers"] = {vp=0, isCharacter=true, id=1790},
    ["CC1 Rachel Summers"] = {vp=0, isCharacter=true,},
    ["TU90 Tempestade"] = {vp=0, isCharacter=true, id=5964},
    ["TU Tempestade"] = {vp=0, isCharacter=true, id=4924},
    ["AA Tempestade"] = {vp=0, isCharacter=true, id=8856},
    ["IW2 Tempestade"] = {vp=0, isCharacter=true, id=7537},
    ["PROMO Fanático"] = {vp=0, isCharacter=true,},
    ["PROMO Medusa"] = {vp=0, isCharacter=true, id=9617},
    ["R2 Aniquilador (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=3513},
    ["SW Eve Bakian Nova Corp (Character)"] = {vp=0, isCharacter=true, id=7450},
    ["IW2 Surfista Prateado"] = {vp=0, isCharacter=true, id=6916},
    ["TU90 Homem-Aranha"] = {vp=0, isCharacter=true, id=8556},
    ["IW2 Tocha Humana"] = {vp=0, isCharacter=true, id=7162},
    ["AA Tocha Humana"] = {vp=0, isCharacter=true, id=9402},
    ["TU Noturno"] = {vp=0, isCharacter=true, id=8366},
    ["TU90 Jean Grey"] = {vp=0, isCharacter=true, id=8542},
    ["TU Jean Grey"] = {vp=0, isCharacter=true, id=7728},
    ["CO1 Vampira"] = {vp=0, isCharacter=true, id=9021},
    ["MS Lilith"] = {vp=0, isCharacter=true,},
    ["CO4 Pantera Negra"] = {vp=0, isCharacter=true, id=9056},
    ["CO7 Bill Raio Beta"] = {vp=2, isHero=true, cost=7, id=5663},
    ["CO12 Demolidor"] = {vp=0, isCharacter=true,},
    ["IW4 Demolidor"] = {vp=0, isCharacter=true, id=5186},
    ["AA Demolidor"] = {vp=0, isCharacter=true, id=9016},
    ["CO1 Charles Xavier Professor X"] = {vp=0, isCharacter=true, id=1664},
    ["MS Morbius"] = {vp=0, isCharacter=true,},
    ["R5 Doctor Doom (Level 1)"] = {vp=4, isCharacter=true,},
    ["DA Doctor Doom"] = {vp=0, isCharacter=true, id=7612},
    ["MS Alioth"] = {vp=0, isCharacter=true,},
    ["PROMO Speed"] = {vp=0, isCharacter=true, id=5207},
    ["KIB Wasp (Character)"] = {vp=0, isCharacter=true, id=6271},
    ["CW2 Quicksilver (Character)"] = {vp=0, isCharacter=true,},
    ["CO12 Blade"] = {vp=0, isCharacter=true,},
    ["IW5 Falcon"] = {vp=0, isCharacter=true,},
    ["IW5 Elektra"] = {vp=0, isCharacter=true,},
    ["KIB Nova Richard Rider (Character)"] = {vp=0, isCharacter=true, id=6248},
    ["PROMO Nova Ko-Rel"] = {vp=0, isCharacter=true,},
    ["R2 Nova Richard Rider (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=9521},
    ["R2 Nova Richard Rider (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=1544},
    ["R2 Nova Richard Rider (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=9274},
    ["CC1 Nova Sam Alexander"] = {vp=0, isCharacter=true,},
    ["PROMO Werewolf by Night"] = {vp=0, isCharacter=true, id=8395},
    ["CO10 Earth X Hulk"] = {vp=0, isCharacter=true,},
    ["CO10 Earth X Nova"] = {vp=0, isCharacter=true,},
    ["CO10 Deadpool"] = {vp=0, isCharacter=true,},
    ["CO10 Earth X Thor"] = {vp=0, isCharacter=true,},
    ["CO10 Earth X Iron Man"] = {vp=0, isCharacter=true,},
    ["CW Mephisto (Level 3)"] = {vp=0, isVillain=true, isCharacter=true, cost=15, id=1354},
    ["CO2 Shuri"] = {vp=0, isCharacter=true, id=6272},
    ["CO4 The Living Tribunal"] = {vp=0, isCharacter=true, id=5711},
    ["CO1 Doctor Strange"] = {vp=0, isCharacter=true, id=4767},
    ["MS Rocket Raccoon (Character)"] = {vp=0, isCharacter=true,},
    ["PROMO Bullseye (Character)"] = {vp=0, isCharacter=true, id=6437},
    ["TU90 Deadpool"] = {vp=0, isCharacter=true, id=9762},
    ["SW Deadpool (Character)"] = {vp=0, isCharacter=true, id=7597},
    ["IW5 Deadpool"] = {vp=0, isCharacter=true,},
    ["CO3 Colossus"] = {vp=0, isCharacter=true, id=4678},
    ["CW Agatha Harkness (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=1749},
    ["CO3 Magik"] = {vp=0, isCharacter=true, id=8002},
    ["IW3 Boomerang"] = {vp=0, isCharacter=true, id=6447},
    ["CO3 Ultron West Coast Avenger"] = {vp=0, isCharacter=true, id=7470},
    ["TU Blue Marvel"] = {vp=0, isCharacter=true, id=6952},
    ["DA Magneto"] = {vp=0, isCharacter=true, id=6936},
    ["PROMO Luke Cage"] = {vp=0, isCharacter=true, id=3063},
    ["R4 Sentry (Level 2)"] = {vp=6, isVillain=true, isCharacter=true, cost=12,},
    ["SW3 Donald Blake/Thor"] = {vp=0, isCharacter=true,},
    ["CO7 Gamora"] = {vp=1, isHero=true, cost=5, id=1995},
    ["TU Morph"] = {vp=0, isCharacter=true, id=8441},
    ["R1 Iron Man (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=1638},
    ["R1 Iron Man (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=5267},
    ["IW2 Spider-Gwen"] = {vp=0, isCharacter=true, id=6290},
    ["AA Spider-Gwen"] = {vp=0, isCharacter=true, id=9773},
    ["CO11 Iron Goblin"] = {vp=0, isCharacter=true,},
    ["CO11 Hydra Cap"] = {vp=0, isCharacter=true,},
    ["CO11 Sentient Armor"] = {vp=0, isCharacter=true,},
    ["TV Venom MC"] = {vp=0, isCharacter=true,},
    ["IW3 Venom"] = {vp=0, isCharacter=true, id=4535},
    ["CO1 Nova Sam Alexander"] = {vp=0, isCharacter=true, id=4559},

-- MC Tier 3
    ["CW Scarlet Witch (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=7569},
    ["CW Captain Marvel (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=9713},
    ["KIB Captain Marvel (Character)"] = {vp=0, isCharacter=true, id=3416},
    ["CO9 Captain Marvel"] = {vp=0, isCharacter=true,},
    ["CO1 Captain America"] = {vp=0, isCharacter=true, id=3552},
    ["C2 Brother Voodoo"] = {vp=0, isCharacter=true, id=7928},
    ["CO5 Mojo"] = {vp=0, isCharacter=true, id=1365},
    ["IW5 Northstar"] = {vp=0, isCharacter=true,},
    ["PROMO Shanna"] = {vp=0, isCharacter=true, id=4349},
    ["CO5 Loki"] = {vp=0, isCharacter=true, id=3520},
    ["RC Kingpin"] = {vp=0, isCharacter=true,},
    ["PROMO Carnage"] = {vp=0, isCharacter=true, id=3470},
    ["CO4 US Agent"] = {vp=0, isCharacter=true, id=9854},
    ["SW2 Ant-Man"] = {vp=0, isCharacter=true,},
    ["MS Man-Thing"] = {vp=0, isCharacter=true,},
    ["IW5 Man-Thing"] = {vp=0, isCharacter=true,},
    ["IW1 Man-Thing"] = {vp=0, isCharacter=true, id=8024},
    ["SW Hulk (Character)"] = {vp=0, isCharacter=true, id=2165},
    ["R5 Hulk (Level 3)"] = {vp=0, isCharacter=true,},
    ["R5 Hulk (Level 1)"] = {vp=4, isCharacter=true,},
    ["MARVEL Hulk"] = {vp=0, isCharacter=true, id=1930},
    ["IW5 Hulk"] = {vp=0, isCharacter=true,},
    ["PROMO She-Hulk"] = {vp=0, isCharacter=true,},
    ["CO9 Rachel Summers"] = {vp=0, isCharacter=true,},
    ["CO9 She-Hulk"] = {vp=0, isCharacter=true,},
    ["R2 Annihilus (Level 2)"] = {vp=6, isVillain=true, isCharacter=true, cost=12, id=8671},
    ["IW3 Annihilus"] = {vp=0, isCharacter=true, id=5058},
    ["R4 Thor (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12,},
    ["R4 Thor (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9,},
    ["AA Thor"] = {vp=0, isCharacter=true, id=5212},
    ["CO4 Groot"] = {vp=0, isCharacter=true, id=3892},
    ["TV Spider-Man"] = {vp=0, isCharacter=true,},
    ["R3 Speed Demon (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9,},
    ["IW2 Red She-Hulk"] = {vp=0, isCharacter=true, id=3529},
    ["TV Winter Soldier"] = {vp=0, isCharacter=true,},
    ["ST The Punisher (Character)"] = {vp=0, isCharacter=true,},
    ["CO2 Hawkeye"] = {vp=0, isCharacter=true, id=8690},
    ["CW Attuma (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=5214},
    ["TV Daredevil"] = {vp=7, isHero=true, isBoss=true, cost=14,},
    ["IW5 Demolidor"] = {vp=0, isCharacter=true,},
    ["RC Doutor Octopus"] = {vp=0, isCharacter=true,},
    ["IW5 Adam Warlock"] = {vp=3, isHero=true, isDefense=true, cost=8,},
    ["CO5 Mastermind"] = {vp=0, isCharacter=true, id=9156},
    ["MARVEL Vision"] = {vp=0, isCharacter=true, id=4366},
    ["MARVEL Sabertooth"] = {vp=2, isVillain=true, cost=7, id=5005},
    ["R5 Doctor Doom (Level 3)"] = {vp=0, isCharacter=true,},
    ["IW3 Tiger Shark"] = {vp=0, isCharacter=true, id=9937},
    ["IW3 Emma Frost"] = {vp=0, isCharacter=true, id=5604},
    ["RC Lizard"] = {vp=0, isCharacter=true,},
    ["CO7 Giganto (Character)"] = {vp=0, isCharacter=true, id=5931},
    ["CW2 Zombie Nova Richard Rider"] = {vp=0, isCharacter=true,},
    ["CW2 Annihilus (Character)"] = {vp=0, isCharacter=true,},
    ["CW2 Zombie Falcon"] = {vp=0, isCharacter=true,},
    ["CW2 Elektra"] = {vp=0, isCharacter=true,},
    ["IW2 Mantis"] = {vp=0, isCharacter=true, id=8659},
    ["AA Angel"] = {vp=0, isCharacter=true, id=4064},
    ["RC Elektra"] = {vp=0, isCharacter=true,},
    ["MARVEL Nova Richard Rider"] = {vp=0, isHero=true, cost=5, id=3364},
    ["IW1 Hawkeye"] = {vp=0, isCharacter=true, id=5057},
    ["CO7 Killmonger (Character)"] = {vp=0, isCharacter=true, id=8064},
    ["MS Swarm"] = {vp=0, isCharacter=true,},
    ["IW4 Valkyrie Brunnhilde (Character)"] = {vp=0, isCharacter=true, id=8599},
    ["KIB Doctor Strange (Character)"] = {vp=0, isCharacter=true, id=1485},
    ["CC1 Doctor Strange"] = {vp=0, isCharacter=true,},
    ["IW5 Doutor Estranho"] = {vp=0, isCharacter=true,},
    ["DA Bullseye"] = {vp=0, isCharacter=true, id=7114},
    ["CO1 Polaris"] = {vp=0, isCharacter=true,},
    ["MARVEL Deadpool"] = {vp=0, isCharacter=true, id=8350},
    ["IW3 Legion"] = {vp=0, isCharacter=true, id=5951},
    ["CO5 Blizzard"] = {vp=0, isCharacter=true, id=6393},
    ["RC Black Cat Promo"] = {vp=0, isCharacter=true,},
    ["AA Black Widow"] = {vp=0, isCharacter=true, id=7760},
    ["R4 Sentry (Level 3)"] = {vp=0, isVillain=true, isCharacter=true, cost=15,},
    ["DA Sentry"] = {vp=0, isCharacter=true, id=3525},
    ["DA Grey Hulk Joe Fixit"] = {vp=0, isCharacter=true, id=3910},
    ["TV Iron Man"] = {vp=0, isCharacter=true,},
    ["SW Iron Man (Character)"] = {vp=0, isCharacter=true, id=7128},
    ["MARVEL Iron Man"] = {vp=0, isCharacter=true, id=2144},
    ["DA Venom"] = {vp=0, isCharacter=true, id=7382},
    ["IW4 Domino"] = {vp=0, isCharacter=true, id=4774},
    ["KIB Namor (Character)"] = {vp=0, isCharacter=true, id=1386},
    ["MARVEL Namor"] = {vp=0, isCharacter=true, id=3422},
    ["IW1 Ka-Zar (Character)"] = {vp=0, isCharacter=true, id=7227},

-- MC Tier 4
    ["TU Morfo"] = {vp=0, isCharacter=true, id=4758},
    ["CW Capitã Marvel (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=7179},
    ["MS Agatha Harkness"] = {vp=0, isCharacter=true,},
    ["MS Capitã Marvel (Character)"] = {vp=0, isCharacter=true,},
    ["PROMO Falcão de Aço"] = {vp=0, isCharacter=true, id=3482},
    ["ST Gambit (Character)"] = {vp=0, isCharacter=true,},
    ["R3 Mercúrio (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12,},
    ["PROMO Imperador Stark"] = {vp=0, isCharacter=true,},
    ["CW Hulk (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=6529},
    ["DA Aniquilador"] = {vp=0, isCharacter=true, id=8933},
    ["R4 Thor (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15,},
    ["MS Cavaleiro da Lua"] = {vp=0, isCharacter=true,},
    ["TV Miles Morales"] = {vp=0, isCharacter=true,},
    ["CO2 Kate Bishop"] = {vp=0, isCharacter=true, id=6182},
    ["MS Wolverine"] = {vp=0, isCharacter=true,},
    ["CW2 Homem de Ferro 2099 (Character)"] = {vp=0, isCharacter=true,},
    ["CO5 Vulcano"] = {vp=0, isCharacter=true, id=4170},
    ["DA Elektra"] = {vp=0, isCharacter=true, id=6998},
    ["MS Encantor"] = {vp=0, isCharacter=true,},
    ["CW Mefisto (Level 1)"] = {vp=4, isVillain=true, isCharacter=true, cost=9, id=7822},
    ["IW3 Rei das Sombras"] = {vp=0, isCharacter=true, id=1367},
    ["CO7 Thanos (Character)"] = {vp=0, isCharacter=true, id=7493},
    ["AA Senhor das Estrelas"] = {vp=0, isCharacter=true, id=1152},
    ["CO9 Máquina  de Combate"] = {vp=0, isCharacter=true,},
    ["CW Namor (Level 2)"] = {vp=6, isHero=true, isCharacter=true, cost=12, id=6360},
    ["CW Namor (Level 1)"] = {vp=4, isHero=true, isCharacter=true, cost=9, id=8514},
    
-- MC Tier 5
    ["R3 Demônio da  Velocidade (Level 2)"] = {vp=6, isVillain=true, isCharacter=true, cost=12,},
    ["KIB Sr. Fantástico (Character)"] = {vp=0, isCharacter=true, id=9345},
    ["KIB Charles Xavier Professor X (Character)"] = {vp=0, isCharacter=true, id=2415},
    ["R5 Doutor Destino (Level 2)"] = {vp=6, isCharacter=true,},
    ["PROMO Ultron"] = {vp=0, isCharacter=true,},
    ["CO11 Homem de Ferro V15"] = {vp=0, isCharacter=true,},
    ["CW Namor (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=4419},

-- MC Tier 6
    ["R1 Carnificina (Level 3)"] = {vp=0, isVillain=true, isCharacter=true, cost=15, id=8846},
    ["CW Attuma (Level 2)"] = {vp=6, isVillain=true, isCharacter=true, cost=12, id=8779},
    ["CO5 Super-Skrull"] = {vp=0, isCharacter=true, id=7724},
    ["IW3 O Sentinela"] = {vp=0, isCharacter=true, id=9882},
    ["R1 Homem de Ferro (Level 3)"] = {vp=0, isHero=true, isCharacter=true, cost=15, id=8677},

--Transformadas
    ["MS Defender"] = {vp=1, isStarter=true, cost=0,}, -- Transformed
    ["MS A Poderosa Thor"] = {vp=1, isHero=true, cost=6,},
    ["MS Thor, Deus do Trovão"] = {vp=1, isHero=true, cost=4,},
    ["MS Morbius, O Vampiro"] = {vp=2, isVillain=true, cost=6,},
    ["MS A Poderosa Thor, corrompida"] = {vp=2, isVillain=true, cost=5,},
    ["MS Coração Negro, O Príncipe do Inferno"] = {vp=1, isVillain=true, cost=6,},
    ["MS Darkhold: O Tomo Negro"] = {vp=2, isEquipment=true, cost=5,},
    ["Promo Doutor Estranho, Mago Supremo"] = {vp=0, isCharacter=true,},

--Chutes
    ["R5 Dias de um Futuro Esquecido"] = {vp=1, cost=3,},
    ["RC O Tentáculo"] = {vp=1, isVillain=true, cost=3,},
    ["MS Ritual Sombrio"] = {vp=1, cost=3,},
    ["CW2 Voadora"] = {vp=1, isAttack=true, cost=3,},
    ["R4 Alteração de Probabilidade"] = {vp=1, isSuperPower=true, cost=3,},
    ["CW Força Intensificada"] = {vp=1, isStarter=true, cost=3},
    ["KIB Sacrifício Final"] = {vp=1, cost=3, id=9145},
    ["R2 Arsenal Psíquico"] = {vp=1, cost=3, id=0},
    ["R3 Velocidade da Luz"] = {vp=1, cost=3,},


--Refens
    ["RC Rick Jones"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Dakota North"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC J. Jonah Jamason"] = {vp=0, isHostage=true, isDefense=true, isOngoing=true, cost=2,},
    ["RC Karen Page"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Sharon Carter"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Dr. Ashley Kafka"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Foggy Nelson"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Ben Urich"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Dr. Elihas Starr"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Tia May"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Harry Osborn"] = {vp=0, isHostage=true, isOngoing=true, cost=2,},
    ["RC Silvio Manfredi"] = {vp=0, isHostage=true, isDefense=true, isOngoing=true, cost=2,},
    ["RC Edwin Jarvis"] = {vp=0, isHostage=true, isDefense=true, isOngoing=true, cost=2,},
    ["RC Senador Robert Kelly"] = {vp=0, isHostage=true, isDefense=true, isOngoing=true, cost=2,},

--Equipamento
    ["AA Joia da Mente"] = {vp=0, isEquipment=true, isExpPowerRing=true, isAttack=true, cost=5, id=7910},
    ["AA A Joia do Poder"] = {vp=0, isEquipment=true, isExpPowerRing=true, isDefense=true, cost=5, id=5382},
    ["R2 A Joia do Poder"] = {vp=1, isEquipment=true, isPowerRing=true, isDefense=true, cost=5, id=6406},
    ["IW5 A Manopla do Infinito"] = {vp=3, isEquipment=true, isPowerRing=true, cost=8,},
    ["MARVEL A Joia da Alma"] = {vp=1, isEquipment=true, isPowerRing=true, cost=3, id=1737},
    ["CW2 A Joia do Poder"] = {vp=2, isEquipment=true, isPowerRing=true, cost=6,},
    ["IW2 A Joia da Alma"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=7525},
    ["AA A Joia do Espaço"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=7121},
    ["AA A Joia da Realidade"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=9741},
    ["AA A Joia do Espaço"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=8012},
    ["IW2 A Joia do Tempo"] = {vp=0, isEquipment=true, isExpPowerRing=true, cost=5, id=9986},
    ["CW2 A Joia da Mente"] = {vp=2, isEquipment=true, isPowerRing=true, cost=6,},
    ["R2 A Joia da Mente"] = {vp=1, isEquipment=true, isPowerRing=true, isAttack=true, cost=4, id=7365},
    ["CO12 Santuário II"] = {vp=1, isEquipment=true, cost=4,},
    ["CO11 Espada de Ébano"] = {vp=2, isEquipment=true, cost=6,},
    ["MARVEL Tridente de Netuno"] = {vp=1, isEquipment=true, cost=3, id=8914},
    ["R5 Cérebro"] = {vp=2, isEquipment=true, cost=7,},
    ["RC Cetro de Controle Cósmico"] = {vp=2, isEquipment=true, cost=6,},
    ["SW Escudo do Treinador"] = {vp=2, isEquipment=true, isOngoing=true, cost=6, id=6668},
    ["R5 Sentinelas de Ultron"] = {vp=1, isEquipment=true, cost=3,},
    ["CO11 Pássaro Negro"] = {vp=2, isEquipment=true, cost=4,},
    ["KIB All-Black A Necroespada"] = {vp=1, isEquipment=true, isMetal=true, cost=3, id=9801},
    ["CO9 Martelo Universal"] = {vp=1, isEquipment=true, isDefense=true, cost=4,},
    ["MARVEL Garras de Adamantium"] = {vp=1, isEquipment=true, cost=3, id=1120},
    ["CO7 Cubo Cósmico"] = {vp=2, isEquipment=true, cost=7, id=5975},
    ["R4 Carro do Justiceiro"] = {vp=1, isEquipment=true, cost=3,},
    ["C1 Tentáculos do Doutor Octopus"] = {vp=1, isEquipment=true, cost=3, id=5736},
    ["CW Espada da Alma"] = {vp=1, isEquipment=true, cost=5, id=4105},
    ["TU90 Mochila a Jato"] = {vp=1, isEquipment=true, cost=4, id=7672},
    ["C2 Facas de Vibranium"] = {vp=1, isEquipment=true, cost=2, id=1087},
    ["RC Destruidor de Gelo"] = {vp=2, isEquipment=true, isAttack=true, cost=6,},
    ["CW2 Bug-Aranha"] = {vp=1, isEquipment=true, cost=2,},
    ["TU90 Blaster"] = {vp=1, isEquipment=true, cost=2, id=4355},
    ["CO5 Talária Sandálias Aladas"] = {vp=0, isEquipment=true, cost=3, id=9518},
    ["CW2 Mjolnir"] = {vp=1, isEquipment=true, cost=4,},
    ["TU90 Rastreador-Aranha"] = {vp=1, isEquipment=true, cost=3, id=8155},
    ["CW2 Flecha Explosiva"] = {vp=1, isEquipment=true, isAttack=true, cost=4,},
    ["CW2 Adagas Sai"] = {vp=1, isEquipment=true, cost=3,},
    ["RC Excalibur"] = {vp=1, isEquipment=true, isDefense=true, cost=3,},
    ["R4 Armadura do Destruidor"] = {vp=2, isEquipment=true, isDefense=true, cost=7,},
    ["CO5 Ferrão da Viúva"] = {vp=0, isEquipment=true, cost=3, id=9705},
    ["KIB Vírus Legado"] = {vp=1, isEquipment=true, isMetal=true, cost=4, id=8045},
    ["IW2 Armadura de Adamantium"] = {vp=4, isEquipment=true, isMetal=true, isDefense=true, cost=9, id=6085},
    ["KIB K-44"] = {vp=1, isEquipment=true, isMetal=true, cost=2, id=6081},
    ["TU90 Bea e Arthur"] = {vp=1, isEquipment=true, cost=2, id=1253},
    ["MS Capa da Levitação"] = {vp=2, isEquipment=true, cost=7},
    ["R5 Exército de Sentinelas"] = {vp=2, isEquipment=true, cost=5,},
    ["CO12 Arma Elemental"] = {vp=1, isEquipment=true, isDefense=true, cost=5,},
    ["IW4 Mapa Holográfico"] = {vp=1, isEquipment=true, isOngoing=true, cost=4, id=3112},
    ["R3 Portal Temporal"] = {vp=3, isEquipment=true, cost=7,},
    ["RC Moto-Aranha"] = {vp=1, isEquipment=true, cost=4,},
    ["IW3 Portão Eterno"] = {vp=1, isEquipment=true, isDefense=true, cost=4, id=5317},
    ["TU90 Pernas Expansíveis"] = {vp=1, isEquipment=true, cost=1, id=6753},
    ["TU Milano"] = {vp=2, isEquipment=true, isDefense=true, cost=7, id=8729},
    ["R1 Bug-Aranha"] = {vp=1, isEquipment=true, cost=3, id=9093},
    ["CW Cetro de Loki"] = {vp=1, isEquipment=true, isAttack=true, cost=4, id=4960},
    ["RC Bastão Duplo"] = {vp=1, isEquipment=true, cost=2,},
    ["RC Ejetores de Gás"] = {vp=2, isEquipment=true, isAttack=true, isBribe=true, cost=5,},
    ["RC Taco de Baseball"] = {vp=1, isEquipment=true, cost=3,},
    ["IW5 Matadora de Deuses MK II"] = {vp=3, isEquipment=true, isOngoing=true, isDefense=true, cost=9,},
    ["R5 Bombas-Abóbora"] = {vp=1, isEquipment=true, cost=2,},
    ["CO11 A Joia da Realidade"] = {vp=1, isEquipment=true, isPowerRing=true, cost=3,},
    ["TV Escudo do Capitão América"] = {vp=1, isEquipment=true, cost=5,},
    ["R3 Olho de Agamotto"] = {vp=3, isEquipment=true, cost=6,},
    ["CC1 Capacete com Chifres"] = {vp=1, isEquipment=true, cost=4,},
    ["IW4 O Cajado do Um"] = {vp=1, isEquipment=true, cost=3, id=3950},
    ["RC Espingarda Infernal"] = {vp=1, isEquipment=true, cost=4, isBribe=true,},
    ["DA Corrente de Fogo Infernal"] = {vp=1, isEquipment=true, cost=3, id=4929},
    ["TU90-2 Diário de Mary Jane"] = {vp=1, isEquipment=true, cost=2,},
    ["TV Hulkbuster"] = {vp=1, isEquipment=true, cost=3, isOngoing=true, isBribe=true,},
    ["MARVEL Bastões de Choque"] = {vp=1, isEquipment=true, isDefense=true, cost=2, id=9914},
    ["CO9 Varinha de Watoomb"] = {vp=1, isEquipment=true, isDefense=true, cost=5,},
    ["CO11 Cartão de Visita"] = {vp=1, isEquipment=true, cost=4,},
    ["AA Aranha-Bot"] = {vp=1, isEquipment=true, isDefense=true, cost=4, id=3517},
    ["CO7 Cadeira Flutuante"] = {vp=2, isEquipment=true, isDefense=true, cost=6, id=1997},
    ["DA Pé de Cabra do Destruidor"] = {vp=1, isEquipment=true, cost=4, id=1820},
    ["IW5 Libertadora"] = {vp=2, isEquipment=true, cost=5,},
    ["IW5 Hellnir"] = {vp=2, isEquipment=true, cost=6,},
    ["TU90-2 FOguete Imprudente"] = {vp=1, isEquipment=true, isAttack=true, cost=5,},
    ["CO6 Quinjet"] = {vp=1, isEquipment=true, isDefense=true, cost=3, id=4272},
    ["R1 Dardos Crescentes"] = {vp=1, isEquipment=true, isDefense=true, cost=4, id=4406},
    ["AA Os Dez Anéis"] = {vp=1, isEquipment=true, cost=4, id=3101},
    ["R5 Soro do Super Soldado"] = {vp=1, isEquipment=true, cost=4,},
    ["AA Fantasticarro"] = {vp=1, isEquipment=true, isDefense=true, cost=3, id=7652},
    ["RC Soro do Duende"] = {vp=1, isEquipment=true, cost=4,},
    ["SW Bug-Aranha"] = {vp=1, isEquipment=true, isDefense=true, isOngoing=true, cost=3, id=3999},
    ["TV Espada Quântica"] = {vp=1, isEquipment=true, cost=4},
    ["RC Mini Lançador de Mísseis"] = {vp=1, isEquipment=true, isDefense=true, cost=5,},
    ["AA Lentes Hipnóticas"] = {vp=2, isEquipment=true, isAttack=true, cost=7, id=2081},
    ["RC Armas Brancas"] = {vp=1, isEquipment=true, isAttack=true, cost=4,},
    ["TU Detonador"] = {vp=1, isEquipment=true, isOngoing=true, cost=3, id=4563},
    ["KIB Rompe-Tormentas"] = {vp=1, isEquipment=true, isDefense=true, cost=3, id=4050},
    ["RC Planador Goblin"] = {vp=1, isEquipment=true, isBribe=true, cost=3,},
    ["R5 Cristal M'kraan"] = {vp=1, isEquipment=true, cost=4,},
    ["IW4 I.M.A. Exo-Traje"] = {vp=1, isEquipment=true, isOngoing=true, cost=2, id=3549},
    ["CO10 Tanque de Fusão de Adamantium"] = {vp=-2, isEquipment=true, isAttack=true, isTimeLineUp=true, cost=7,},
    ["CO12 Lançadores de Teia"] = {vp=1, isEquipment=true, cost=4,},
    ["R5 Frogjolnir"] = {vp=2, isEquipment=true, cost=6,},
    ["MS Gema Carmesim de Cyttorak"] = {vp=2, isEquipment=true, isAttack=true, cost=6,},
    ["MS Rifle de Telecinese"] = {vp=1, isEquipment=true, cost=2,},
    ["MS Tomos Antigos"] = {vp=1, isEquipment=true, cost=3,},
    ["MS O Livro de Cagliostro"] = {vp=1, isEquipment=true, cost=2,},
    ["CO3 Armadura do Fluxo Temporal"] = {vp=1, isEquipment=true, isDefense=true, cost=3, id=7008},
    ["IW5 O Nulificador Total"] = {vp=2, isEquipment=true, cost=7,},
    


--Superpoder
    ["TU90-2 Divindade Elemental"] = {vp=1, isSuperPower=true, cost=2,},
    ["RC Força Bruta"] = {vp=2, isSuperPower=true, isBribe=true, cost=6,},
    ["SW3 Supremacia Arcana"] = {vp=1, isSuperPower=true, cost=5,},
    ["RC Pancada Sísmica"] = {vp=1, isSuperPower=true, isBribe=true, cost=3,},
    ["RC Fortuna Felina"] = {vp=1, isSuperPower=true, cost=4,},
    ["RC Salve Hydra!"] = {vp=3, isSuperPower=true, isBribe=true, cost=7,},
    ["CO11 Cartas Explosivas"] = {vp=2, isSuperPower=true, cost=3,},
    ["TV Ira do Titã"] = {vp=1, isSuperPower=true, cost=5, isAttack=true,},
    ["R5 Sentidos Apurados"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW4 Avante Vingadores!"] = {vp=1, isSuperPower=true, isOngoing=true, cost=5, id=7223},
    ["SW Raio Cósmico"] = {vp=1, isSuperPower=true, cost=5, id=3498},
    ["TU Crescimento Desenfreado"] = {vp=2, isSuperPower=true, isOngoing=true, cost=6, id=6409},
    ["KIB Revelação Arcana"] = {vp=1, isSuperPower=true, cost=4, id=2703},
    ["R3 Batalhão de Neve"] = {vp=1, isSuperPower=true, cost=3,},
    ["R5 Aliança Perigosa"] = {vp=1, isSuperPower=true, cost=2,},
    ["CW Absorção de Choque"] = {vp=1, isSuperPower=true, cost=4, id=8968},
    ["R4 União Mutante"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW5 Abraço Parasita"] = {vp=2, isSuperPower=true, cost=5,},
    ["CC1 Ressurreição"] = {vp=1, isSuperPower=true, cost=5,},
    ["R5 Arsenal Orgânico"] = {vp=1, isSuperPower=true, cost=4,},
    ["CW2 Grito Hipersônico"] = {vp=2, isSuperPower=true, isAttack=true, cost=5,},
    ["MS Escudo dos Serafins"] = {vp=1, isSuperPower=true, isDefense=true, isOngoing=true, cost=5,},
    ["MARVEL Rajada Óptica"] = {vp=2, isSuperPower=true, cost=6, id=9007},
    ["CO3 Potencial Ilimitado"] = {vp=1, isSuperPower=true, cost=4, id=8431},
    ["DA Unibeam"] = {vp=1, isSuperPower=true, cost=4, id=5429},
    ["CO12 Insanidade"] = {vp=1, isSuperPower=true, cost=4,},
    ["R5 Plano Mestre"] = {vp=1, isSuperPower=true, cost=4,},
    ["R1 Vigília Urbana"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=1709},
    ["CO11 Fumaça Espiritual"] = {vp=1, isSuperPower=true, cost=3,},
    ["CO5 Em Chamas!"] = {vp=0, isSuperPower=true, cost=5, id=9446},
    ["MS Fúria Espelhada"] = {vp=1, isSuperPower=true, cost=3,},
    ["IW2 Campo de força Invisível"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=5857},
    ["CO11 Impacto Brutal"] = {vp=1, isSuperPower=true, cost=4,},
    ["IW5 Força Fênix"] = {vp=3, isSuperPower=true, cost=8,},
    ["TU Agilidade Acrobática"] = {vp=1, isSuperPower=true, isDefense=true, cost=1, id=6956},
    ["R4 Feixe de Neutralização"] = {vp=1, isSuperPower=true, cost=4,},
    ["TU Eletrocinese"] = {vp=1, isSuperPower=true, isAttack=true, cost=4, id=7492},
    ["R4 Força Olímpica"] = {vp=1, isSuperPower=true, cost=4,},
    ["R2 Adaga Psíquica"] = {vp=1, isSuperPower=true, cost=5, id=8463},
    ["AA Invisibilidade"] = {vp=1, isSuperPower=true, isDefense=true, isOngoing=true, cost=3, id=1757},
    ["MS Forma Astral"] = {vp=2, isSuperPower=true, isDefense=true, cost=6},
    ["RC Hospedeiro Instável"] = {vp=1, isSuperPower=true, isBribe=true, cost=5,},
    ["R4 Ofensiva Brutal"] = {vp=1, isSuperPower=true, cost=2,},
    ["AA Domínio Molecular"] = {vp=2, isSuperPower=true, cost=7, id=8004},
    ["R4 Velocidade Cósmica"] = {vp=2, isSuperPower=true, cost=7,},
    ["TU Absorção de Poderes"] = {vp=1, isSuperPower=true, cost=4, id=7566},
    ["R5 Arremesso Especial"] = {vp=2, isSuperPower=true, cost=7,},
    ["AA Solo Sagrado"] = {vp=1, isSuperPower=true, cost=3, id=9273},
    ["R1 Ódio Primal"] = {vp=1, isSuperPower=true, cost=3, id=4867},
    ["CO5 Força em Números"] = {vp=0, isSuperPower=true, cost=5, id=7929},
    ["CO6 Fator de Cura"] = {vp=1, isSuperPower=true, cost=5, id=6212},
    ["IW3 Prisão Ártica"] = {vp=1, isSuperPower=true, cost=6, id=9305},
    ["CW2 Golpe de Misericórdia"] = {vp=1, isSuperPower=true, cost=2,},
    ["CW2 Agilidade Sensorial"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["TU90 Arrancada Imprudente"] = {vp=1, isSuperPower=true, cost=5, id=7275},
    ["RC Controle Absoluto"] = {vp=1, isSuperPower=true, cost=5,},
    ["RC Tudo ou Nada"] = {vp=1, isSuperPower=true, isBribe=true, cost=2,},
    ["CO10 Ruptura Temporal"] = {vp=0, isSuperPower=true, isTimeLineUp=true, cost=6,},
    ["MARVEL Telecinésia"] = {vp=1, isSuperPower=true, cost=3, id=1785},
    ["CW Manipulação do Vazio"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=9799},
    ["CW Fúria Peluda"] = {vp=1, isSuperPower=true, cost=3, id=1856},
    ["CW2 ESMAGA!"] = {vp=2, isSuperPower=true, cost=6,},
    ["RC Engenharia Calculada"] = {vp=1, isSuperPower=true, cost=3,},
    ["CW2 Rajadas Fotônicas"] = {vp=1, isSuperPower=true, cost=3,},
    ["R3 Domínio dos Ventos"] = {vp=2, isSuperPower=true, cost=5,},
    ["CO3 Campos Magnéticos"] = {vp=2, isSuperPower=true, cost=6, id=2002},
    ["TU90-2 Proteção Versátil"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["IW1 Magia do Caos"] = {vp=1, isSuperPower=true, cost=5, id=7327},
    ["TV Trabalho Sujo"] = {vp=1, isSuperPower=true, cost=4, isBribe=true,},
    ["R2 Arsenal Psiônico"] = {vp=1, isSuperPower=true, cost=2, id=6664},
    ["CW Relâmpago"] = {vp=1, isSuperPower=true, isAttack=true, cost=5, id=4550},
    ["MARVEL À Prova de Balas"] = {vp=1, isSuperPower=true, isDefense=true, cost=4, id=4830},
    ["CW2 Tá na Hora do Pau!"] = {vp=1, isSuperPower=true, cost=5,},
    ["TU90 Elo Mental"] = {vp=1, isSuperPower=true, cost=2, id=2049},
    ["R2 Magnetismo"] = {vp=2, isSuperPower=true, cost=6, id=8379},
    ["R3 Teste de Resistência"] = {vp=1, isSuperPower=true,isAttack=true, cost=5,},
    ["R2 Armadura Psiônica"] = {vp=1, isSuperPower=true, isDefense=true, cost=5, id=7210},
    ["SW Aço Orgânico"] = {vp=2, isSuperPower=true, isDefense=true, cost=5, id=2145},
    ["KIB Sentido Aranha"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=5607},
    ["R4 Investida Final"] = {vp=2, isSuperPower=true, cost=6,},
    ["RC Legado de Loucura"] = {vp=1, isSuperPower=true, isBribe=true, cost=3,},
    ["IW1 Deslizamento Glacial"] = {vp=1, isSuperPower=true, isDefense=true, cost=2, id=5262},
    ["R1 Barreira Quântica"] = {vp=2, isSuperPower=true, isDefense=true, cost=6, id=9494},
    ["MS Ponto de Equilibrio"] = {vp=1, isSuperPower=true, cost=3,},
    ["MS Influência Sinistra"] = {vp=1, isSuperPower=true, isAttack=true, cost=3,},
    ["MS Ponto de Ignição"] = {vp=2, isSuperPower=true, isAttack=true, cost=6,},
    ["MS Evolução Forçada"] = {vp=1, isSuperPower=true, cost=2,},
    ["MS Resistência Heroica"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["SW Essência do Trapaceiro"] = {vp=2, isSuperPower=true, cost=6, id=1268},
    ["R3 Investida do Ferrão"] = {vp=2, isSuperPower=true, cost=5,},
    ["TU90 Super Força"] = {vp=2, isSuperPower=true, cost=5, id=3857},
    ["DA Raios Repulsores"] = {vp=1, isSuperPower=true, cost=3, id=2104},
    ["CO10 Onipresença"] = {vp=-3, isSuperPower=true, isOngoing=true, isTimeLineUp=true, cost=6,},
    ["RC Controle Mental"] = {vp=1, isSuperPower=true, isDefense=true, cost=4,},
    ["TU BAMF!"] = {vp=1, isSuperPower=true, isOngoing=true, cost=3, id=4488},
    ["RC Sorte Garantida"] = {vp=1, isSuperPower=true, cost=4,},
    ["CO1 Sobrecarga de Chi"] = {vp=2, isSuperPower=true, cost=6, id=6766},
    ["AA Manipulação da Realidade"] = {vp=1, isSuperPower=true, cost=7, id=5847},

--Vilões
    ["AA Attuma"] = {vp=1, isVillain=true, cost=2, id=1336},
    ["R5 Soprano"] = {vp=1, isVillain=true, cost=3,},
    ["R1 Venom"] = {vp=1, isVillain=true, cost=4, id=4124},
    ["TU M.O.D.O.K."] = {vp=1, isVillain=true, cost=2, id=4500},
    ["CO9 Alto Evolucionário"] = {vp=2, isVillain=true, isDefense=true, cost=6,},
    ["R4 Blob"] = {vp=1, isVillain=true, cost=3,},
    ["R5 Crânio Ardente"] = {vp=1, isVillain=true, cost=3,},
    ["IW5 Carnificina Lobisomem"] = {vp=3, isVillain=true, cost=6,},
    ["R5 Próxima Meia-Noite"] = {vp=1, isVillain=true, cost=3,},
    ["RC Shriek"] = {vp=1, isVillain=true, isDefense=true, cost=5,},
    ["TU Monge do Ódio"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=9000},
    ["CO11 Víbora"] = {vp=1, isVillain=true, cost=5,},
    ["CC1 Escorpião"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
    ["R2 Blastaar"] = {vp=2, isVillain=true, isDefense=true, cost=6, id=4743},
    ["KIB Arcanjo"] = {vp=2, isVillain=true, isMetal=true, isAttack=true, cost=7, id=3061},
    ["CC1 Jaqueta Amarela"] = {vp=1, isVillain=true, isAttack=true, cost=4,},
    ["Marvel Thunderbolts"] = {vp=0, isVillain=true, cost=4, id=9516},
    ["R4 Mamba Negra"] = {vp=2, isVillain=true, cost=4,},
    ["R5 Abutre"] = {vp=1, isVillain=true, cost=2,},
    ["RC Venom"] = {vp=2, isVillain=true, cost=7,},
    ["TV O Consertador"] = {vp=1, isVillain=true, cost=2, isOngoing=true, isBribe=true,},
    ["R5 Homem-Impossível"] = {vp=2, isVillain=true, cost=6,},
    ["RC Rattus"] = {vp=1, isVillain=true, isBribe=true, cost=2,},
    ["R5 Hulk Contra o Mundo"] = {vp=1, isVillain=true, cost=5,},
    ["IW5 Duende Macabro"] = {vp=0, isVillain=true, cost=5,},
    ["CW Coração Negro"] = {vp=1, isVillain=true, cost=3, id=3500},
    ["CO7 O Caído"] = {vp=1, isVillain=true, cost=5, id=7900},
    ["CW2 Homem-Aranha Simbionte"] = {vp=1, isVillain=true, isDefense=true, cost=2,},
    ["CW Titânia"] = {vp=1, isVillain=true, isDefense=true, cost=3, id=5897},
    ["MARVEL Retalho"] = {vp=1, isVillain=true, cost=2, id=1319},
    ["TU Kang"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=1316},
    ["CO11 Carnificina"] = {vp=2, isVillain=true, isAttack=true, cost=6,},
    ["CO9 Elektra"] = {vp=1, isVillain=true, isAttack=true, cost=3,},
    ["KIB Magneto"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=2013},
    ["R3 Mercúrio Zumbi"] = {vp=3, isVillain=true, isAttack=true, cost=7,},
    ["TU Nebula"] = {vp=1, isVillain=true, isOngoing=true, cost=4, id=9940},
    ["DA Supergigante"] = {vp=1, isVillain=true, cost=3, id=4630},
    ["RC Pensador Louco"] = {vp=1, isVillain=true, isBribe=true, cost=4,},
    ["TU Rino"] = {vp=1, isVillain=true, cost=3, id=4158},
    ["IW2 Namor Zumbi"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=9302},
    ["TU90 Pets dos Mestres do Mal"] = {vp=1, isVillain=true, cost=2, id=8228},
    ["TV Muse"] = {vp=1, isVillain=true, cost=3, isBribe=true,},
    ["RC Gatuno"] = {vp=1, isVillain=true, isBribe=true, cost=3,},
    ["RC Pyro"] = {vp=1, isVillain=true, isAttack=true, isBribe=true, cost=4,},
    ["CO2 Blade"] = {vp=1, isVillain=true, cost=5, id=6557},
    ["CO9 Víbora"] = {vp=2, isVillain=true, isAttack=true, cost=5,},
    ["CO11 Elektra"] = {vp=1, isVillain=true, cost=4,},
    ["IW5 Esquecimento"] = {vp=3, isVillain=true, cost=6,},
    ["TU Wendigo"] = {vp=1, isVillain=true, isDefense=true, cost=5, id=6650},
    ["KIB Monstro-Aranha"] = {vp=2, isVillain=true, cost=2, id=8624},
    ["CW Abominável"] = {vp=1, isVillain=true, cost=5, id=4747},
    ["R4 Pestilência"] = {vp=2, isVillain=true, isAttack=true, isConfrontation=true, cost=6,},
    ["R2 Ego, o Planeta Vivo"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=4516},
    ["RC Fanático"] = {vp=1, isVillain=true, isDefense=true, cost=4,},
    ["RC Sapo"] = {vp=1, isVillain=true, isBribe=true, cost=5,},
    ["TV Caveira Vermelha"] = {vp=2, isVillain=true, cost=5, isAttack=true,},
    ["TU Homem-Toupeira"] = {vp=1, isVillain=true, isDefense=true, isOngoing=true, cost=2, id=5859},
    ["CO5 Magma"] = {vp=0, isVillain=true, cost=3, id=5922},
    ["TU902 Homem-Fuleiro"] = {vp=1, isVillain=true, cost=5,},
    ["IW5 Homem  de Ferro Sentinela"] = {vp=3, isVillain=true, cost=5,},
    ["TU Cassandra Nova"] = {vp=2, isVillain=true, isAttack=true, cost=6, id=4075},
    ["MARVEL Venom"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=5050},
    ["MS Gabriel Housman"] = {vp=1, isVillain=true, cost=4,},
    ["IW5 Lady Letal"] = {vp=2, isVillain=true, cost=4,},
    ["IW5 Homem de Ferro Cancerverso"] = {vp=3, isVillain=true, cost=6,},
    ["TU Homem Radioativo"] = {vp=1, isVillain=true, cost=3, id=6799},
    ["CW2 Agente Venom"] = {vp=1, isVillain=true, cost=3,},
    ["R5 Cynthia Von Doom"] = {vp=1, isVillain=true, cost=4,},
    ["IW1 Emma Frost"] = {vp=1, isVillain=true, isAttack=true, cost=4, id=3920},
    ["RC Besouro"] = {vp=1, isVillain=true, cost=3,},
    ["DA Líder"] = {vp=1, isVillain=true, cost=2, id=4899},
    ["RC Capitão Louco"] = {vp=2, isVillain=true, cost=6,},
    ["R3 Laser Vivo"] = {vp=2, isVillain=true, cost=6,},
    ["CW Magneto"] = {vp=1, isVillain=true, cost=3, id=6914},
    ["R5 Electro"] = {vp=1, isVillain=true, cost=4,},
    ["R1 Muse"] = {vp=1, isVillain=true, cost=2, id=7511},
    ["RC Morbius"] = {vp=1, isVillain=true, cost=4,},
    ["R5 Hulk Cinza Sr. Tira-teima"] = {vp=2, isVillain=true, cost=5,},
    ["CW Orka"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=4838},
    ["R5 Abominável"] = {vp=2, isVillain=true, cost=7,},
    ["TV Manto e Adaga"] = {vp=1, isVillain=true, cost=4, isOngoing=true, isBribe=true,},
    ["CO11 Lagarto"] = {vp=1, isVillain=true, isDefense=true, cost=3,},
    ["RC Mestre dos Bonecos"] = {vp=1, isVillain=true, cost=2,},
    ["IW4 O Capuz"] = {vp=1, isVillain=true, isOngoing=true, cost=1, id=6259},
    ["R4 Mefisto"] = {vp=2, isVillain=true, isConfrontation=true, cost=5,},
    ["R5 Senhor Negativo"] = {vp=1, isVillain=true, cost=3,},
    ["CW A Ninhada"] = {vp=1, isVillain=true, cost=2, id=3899},
    ["R2 Shocker"] = {vp=1, isVillain=true, cost=3, id=5482},
    ["R3 Vulcan"] = {vp=0, isVillain=true, cost=3,},
    ["R1 Mary Tifoide"] = {vp=1, isVillain=true, cost=5, id=5622},
    ["RC Cabeça de Martelo"] = {vp=0, isVillain=true, isExpBribe=true, cost=7,},
    ["MARVEL Dentes de Sabre"] = {vp=2, isVillain=true, cost=7, id=5005},
    ["MARVEL Legião"] = {vp=1, isVillain=true, cost=2, id=3447},
    ["AA Muse"] = {vp=1, isVillain=true, isAttack=true, cost=3, id=7807},
    ["DA Gárgula Cinzento"] = {vp=1, isVillain=true, cost=4, id=7265},
    ["KIB Mercenário"] = {vp=1, isVillain=true, isMetal=true, isDefense=true, cost=4, id=9630},
    ["MS Alioth"] = {vp=2, isVillain=true, cost=6,},
    ["MS Fanático"] = {vp=1, isVillain=true, isDefense=true, cost=4,},
    ["MS Mímico"] = {vp=1, isVillain=true, cost=3,},


--Heróis
    ["CW Cavaleiro da Lua"] = {vp=1, isHero=true, cost=3, id=7178},
    ["R4 Armadura"] = {vp=2, isHero=true, isDefense=true, cost=5,},
    ["RC Radical"] = {vp=1, isHero=true, cost=5,},
    ["R4 Freyja"] = {vp=2, isHero=true, isBlock=true, blockValue=3, cost=5,},
    ["IW Estrela Polar"] = {vp=1, isHero=true, isOngoing=true, cost=4, id=1791},
    ["RC Jessica Jones"] = {vp=1, isHero=true, isBribe=true, cost=3,},
    ["RC Patriota de Ferro"] = {vp=2, isHero=true, cost=6,},
    ["CW Cosmo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5000},
    ["R5 Cosmo"] = {vp=1, isHero=true, cost=4,},
    ["RC Linda Carter"] = {vp=1, isHero=true, cost=4,},
    ["CW2 Viúva Negra"] = {vp=1, isHero=true, isAttack=true, cost=3,},
    ["IW5 Jeff"] = {vp=2, isHero=true, isDefense=true, cost=7,},
    ["CO11 Demolidor"] = {vp=1, isHero=true, cost=5,},
    ["SW Namor"] = {vp=1, isHero=true, cost=3, id=1049},
    ["CO11 Gavião Arqueiro"] = {vp=2, isHero=true, cost=4,},
    ["IW5 Adam Warlock"] = {vp=3, isHero=true, isDefense=true, cost=8,},
    ["RC Dinossauro Diabólico"] = {vp=1, isHero=true, isDefense=true, cost=3,},
    ["TV Valquíria"] = {vp=1, isHero=true, cost=4, isOngoing=true, isBribe=true,},
    ["CW Tritão"] = {vp=1, isHero=true, cost=3, id=6213},
    ["TV A Coisa"] = {vp=2, isHero=true, cost=6, isBribe=true,},
    ["R4 Howard o Pato"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["TV Goose"] = {vp=1, isHero=true, cost=5, isOngoing=true, isDefense=true,},
    ["IW5 Youndu"] = {vp=2, isHero=true, cost=5,},
    ["R3 Seda"] = {vp=1, isHero=true, cost=4,},
    ["IW2 Capitão Mar-Vell"] = {vp=1, isHero=true, cost=4, id=6613},
    ["R3 Homem de Gelo"] = {vp=1, isHero=true, isAttack=true, cost=4,},
    ["CO9 Falcão"] = {vp=1, isHero=true, isAttack=true, cost=4,},
    ["RC Felina"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=5,},
    ["AS Adam Warlock"] = {vp=2, isHero=true, cost=7, id=7644},
    ["CO10 Namora Terra X"] = {vp=-2, isHero=true, isDefense=true, isTimeLineUp=true, cost=6,},
    ["MS Dr. Michael Morbius"] = {vp=1, isHero=true, cost=4,},
    ["TU Drax"] = {vp=1, isHero=true, cost=4, id=7267},
    ["RC Mancha Solar"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["R1 Miles Morales"] = {vp=1, isHero=true, cost=4, id=5295},
    ["CW Filhos da Meia-Noite"] = {vp=1, isHero=true, isDefense=true, cost=3, id=6352},
    ["RC Misty Knight"] = {vp=2, isHero=true, cost=6,},
    ["SW2 Thor Jane Foster"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["SW Eve Bakian nova corp."] = {vp=1, isHero=true, cost=4, id=1285},
    ["TV Motoqueiro Fantasma"] = {vp=1, isHero=true, cost=3, isBribe=true,},
    ["R5 Coração de Ferro"] = {vp=2, isHero=true, cost=5,},
    ["KIB Sr. Fantástico"] = {vp=1, isHero=true, cost=3, id=6084},
    ["MARVEL Deadpool"] = {vp=1, isHero=true, cost=3, id=6872},
    ["DA Coração de Ferro"] = {vp=1, isHero=true, cost=3, id=8620},
    ["DA Onda"] = {vp=1, isHero=true, cost=2, id=1728},
    ["CO11 Radical"] = {vp=1, isHero=true, cost=4,},
    ["CO1 Punho de Ferro"] = {vp=1, isHero=true, cost=4, id=6666},
    ["IW4 Blink"] = {vp=2, isHero=true, isOngoing=true, cost=6, id=8216},
    ["SW Deadpool"] = {vp=0, isCharacter=true, id=7597},
    ["TU Solaris"] = {vp=1, isHero=true, cost=2, id=9694},
    ["R5 Ciclope"] = {vp=2, isHero=true, cost=6,},
    ["IW5 Domino"] = {vp=2, isHero=true, cost=5,},
    ["DA Maria Hill"] = {vp=1, isHero=true, cost=4, id=8153},
    ["R5 Trish Tilby"] = {vp=1, isHero=true, cost=2,},
    ["RC Cavaleiro da Lua"] = {vp=1, isHero=true, cost=4,},
    ["R3 Míssil"] = {vp=1, isHero=true, cost=3,},
    ["AA Gwen-Aranha"] = {vp=1, isHero=true, cost=3, id=9385},
    ["R5 Ciclope"] = {vp=1, isHero=true, cost=5,},
    ["R4 Falcão"] = {vp=1, isHero=true, isDefense=true, cost=5,},
    ["RC Guarda da Prisão"] = {vp=1, isHero=true, isBribe=true, cost=1,},
    ["CO1 Garota Esquilo"] = {vp=1, isHero=true, isDefense=true, cost=3, id=5755},
    ["RC América Chavez"] = {vp=2, isHero=true, isBribe=true, cost=7,},
    ["AA Psylocke"] = {vp=1, isHero=true, isDefense=true, cost=2, id=6046},
    ["R4 Hércules"] = {vp=1, isHero=true, isConfrontation=true, cost=5,},
    ["CO10 Capitão Britânia Terra X"] = {vp=-2, isHero=true, isTimeLineUp=true, cost=5,},
    ["R2 O Vigia"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7874},
    ["TU Namorita"] = {vp=1, isHero=true, isOngoing=true, cost=3, id=4487},
    ["IW4 Valquíria"] = {vp=2, isHero=true, isDefense=true, cost=6, id=9723},
    ["TU Homem-Múltiplo"] = {vp=1, isHero=true, cost=2, id=1767},
    ["CW Havok"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9933},
    ["TU90 Ciclope"] = {vp=1, isHero=true, isDefense=true, cost=4, id=7161},
    ["RC Happy Hogan"] = {vp=1, isHero=true, isAttack=true, isBribe=true, cost=3,},
    ["AA Jean Grey"] = {vp=1, isHero=true, cost=3, id=8883},
    ["IW1 Wolverine"] = {vp=1, isHero=true, cost=5, id=8902},
    ["CW Irmão Voodoo"] = {vp=1, isHero=true, cost=3, id=6429},
    ["R5 Betty Ross"] = {vp=1, isHero=true, cost=2,},
    ["R5 Mulher-Hulk"] = {vp=2, isHero=true, cost=7,},
    ["CO11 Visão"] = {vp=2, isHero=true, cost=6,},
    ["TU 90-2 Doop"] = {vp=1, isHero=true, cost=4,},
    ["IW5 Jean Grey"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["CO3 Quasar"] = {vp=1, isHero=true, cost=5, id=6299},
    ["SW3 Wolverine"] = {vp=1, isHero=true, cost=5,},
    ["CO11 Homem-Aranha"] = {vp=1, isHero=true, cost=3,},
    ["CC1 Poeira"] = {vp=1, isHero=true, isDefense=true, cost=4,},
    ["IW5 Ciclone"] = {vp=2, isHero=true, cost=7,},
    ["CO12 Micro"] = {vp=1, isHero=true, cost=2,},
    ["TU Marvel Azul"] = {vp=1, isHero=true, isDefense=true, cost=4, id=5808},
    ["R4 Polaris"] = {vp=1, isHero=true, isBlock=true, blockValue=2, cost=4,},
    ["DA Rachel Summers"] = {vp=1, isHero=true, isDefense=true, cost=4, id=8676},
    ["R3 Célere"] = {vp=2, isHero=true, cost=5,},
    ["RC Symbie"] = {vp=1, isHero=true, cost=2,},
    ["CO11 Tocha Humana"] = {vp=2, isHero=true, cost=5,},
    ["R1 Máquina de Combate"] = {vp=1, isHero=true, cost=3, id=7521},
    ["CW2 Demolidor"] = {vp=2, isHero=true, isDefense=true, cost=6,},
    ["R5 Mary Jane"] = {vp=1, isHero=true, cost=4,},
    ["R2 Phyla-Vell"] = {vp=1, isHero=true, cost=3, id=5209},
    ["R5 Vampira"] = {vp=2, isHero=true, cost=6,},
    ["DA Dum Dum Dugan"] = {vp=1, isHero=true, isDefense=true, cost=2, id=5074},
    ["RC Agente Culson"] = {vp=1, isHero=true, isBribe=true, cost=2,},
    ["R1 Blade"] = {vp=1, isHero=true, cost=4, id=4083},
    ["CO2 Angela"] = {vp=1, isHero=true, isDefense=true, cost=4, id=9549},
    ["MS Jane Foster"] = {vp=1, isHero=true, cost=4,},
    ["MS Feiticeira Escarlate"] = {vp=2, isHero=true, cost=7,},
    ["MS Wiccano"] = {vp=1, isHero=true, cost=4,},
    ["MS Madame Teia"] = {vp=1, isHero=true, cost=3,},
    ["MS Cristal"] = {vp=1, isHero=true, cost=3,},
    ["MS Dr. Donald Blake"] = {vp=1, isHero=true, cost=2,},
    ["MS Lupina"] = {vp=1, isHero=true, isDefense=true, cost=2,},
    
--Localizações
    ["TU90 Rua Yancy"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4247},
    ["CW Ilha Muir"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4403},
    ["CO9 Latvéria"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["RC A Balsa"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["R5 Clarim Diário"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
    ["MARVEL Mansão dos Vingadores"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=1617},
    ["TV Madripoor"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["MARVEL Instituto Ravencroft"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7037},
    ["DA Edifício Baxter"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=6434},
    ["R5 Sanctum Sanctorium"] = {vp=2, isLocation=true, isOngoing=true, cost=5,},
    ["R2 Colégio Midtown"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=7408},
    ["TU O Concaverso"] = {vp=1, isLocation=true, isAttack=true, isOngoing=true, cost=5,
    ["TU90 Cidade de Nova York"] = {vp=1, isLocation=true, isOngoing=true, cost=3, id=6643},
    ["IW1 Dimensão de Enxofre"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5570},
    ["RC Terra Selvagem"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["CO1 Wakanda"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=1030},
    ["R3 Nave-Mundo"] = {vp=1, isLocation=true, isOngoing=true, cost=5},
    ["CO2 O Pico"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=6086},
    ["IW5 Olimpo"] = {vp=2, isLocation=true, isOngoing=true, cost=7,},
    ["MARVEL Ponte do Brooklyn"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=8226},
    ["KIB Bar Sem Nome"] = {vp=1, isLocation=true, isDefense=true, isOngoing=true, cost=5, id=7085},
    ["R1 Oficina do Tony Stark"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=5817},
    ["TV Genosha"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["R5 Ilha Flutuante da Hydra"] = {vp=2, isLocation=true, isOngoing=true, cost=6,},
    ["CO3 Zona Negativa"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=6972},
    ["R3 Porta-aviões da S.H.I.E.L.D."] = {vp=1, isLocation=true, isOngoing=true, cost=5},
    ["MARVEL Sala de Perigo"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=5956},
    ["R2 Asteróide M"] = {vp=1, isLocation=true, isOngoing=true, cost=6, id=5400},
    ["MV Instituto Xavier"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=4537},
    ["RC Indústrias Oscorp"] = {vp=1, isLocation=true, isOngoing=true, cost=5,},
    ["C1 A Cozinha do Diabo"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=4657},
    ["TU Ilha dos Monstros"] = {vp=1, isLocation=true, isOngoing=true, cost=4, id=3123},
    ["MARVEL A Área Azul da Lua"] = {vp=1, isLocation=true, isOngoing=true, cost=5, id=9435},
    ["IW2 Atlântida"] = {vp=2, isLocation=true, isOngoing=true, cost=6, id=7099},
    
-- Nemesis Iniciais
    
    ["SP Hulk"] = {vp=4, isHero=true, isBoss=true, isStartBoss=true, cost=8,},
    ["IW2 Apocalipse"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, isOngoing=true, cost=9, id=2179},
    ["TV Radical"] = {vp=4, isHero=true, isStartBoss=true, isBoss=true, cost=8, isDefense=true,},
    ["CO9 Scorn A filha do Carnificina"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, isAttack=true, isOngoing=true, cost=8,},
    ["IW4 Wade Wilson Deadpool"] = {vp=4, isVillain=true, isBoss=true, isOngoing=true, isStartBoss=true, cost=9, id=9473},
    ["IW1 Mandarim"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, cost=9, id=5876},
    ["MARVEL Mandarim"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, cost=8, id=8938},
    ["PROMO Jean Grey"] = {vp=4, isHero=true, isBoss=true, isStartBoss=true, cost=8,},
    ["RE Doutor Destino"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, cost=8,},
    ["CO12 Lagarto"] = {vp=4, isVillain=true, isStartBoss=true, isBoss=true, cost=8,},
    ["CW2 Carnificina"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, isOngoing=true, cost=8,},
    ["CC1 Ymir"] = {vp=4, isVillain=true, isBoss=true, isStartBoss=true, cost=8,},
    ["RC Dum Dum Dugan"] = {vp=4, isHero=true, isStartBoss=true, isBoss=true, cost=8,},
    ["TV Rei das Sombras"] = {vp=4, isVillain=true, isStartBoss=true, isBoss=true, isOngoing=true, cost=8,},
    ["TU Arcade"] = {vp=4, isBoss=true, isStartBoss=true, cost=8, id=4276},
    ["CO11 Homem de Ferro"] = {vp=4, isHero=true, isStartBoss=true, isBoss=true, cost=8,},

-- Nemesis Custo 9
    ["SP Homem-Aranha"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["SP Tigresa"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["SP Magnum"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["ST Gambit"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["TV Fera"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["CO6 Arnim Zola"] = {vp=5, isVillain=true, isBoss=true, cost=9, id=7466},
    ["IW5 Maníaco de Ferro"] = {vp=6, isVillain=true, isBoss=true, cost=9,},
    ["RE Mysterio"] = {vp=5, isVillain=true, isBoss=true, isAttack=true, cost=9,},
    ["RC Homem-Aranha"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["CC1 Aberração Happy Hogan"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["CO12 Víbora"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["RC X-23"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["TV Cobra"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["TV Ossos Cruzados"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["CO11 Vespa"] = {vp=6, isHero=true, isBoss=true, cost=9,},
    ["CW2 Thor Zumbi"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["RC Blade"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["PROMO Falcão"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["CO11 Nova Richard Rider"] = {vp=6, isHero=true, isBoss=true, cost=9,},
    ["MARVEL Mercenário"] = {vp=5, isVillain=true, isBoss=true, cost=9, id=5640},
    ["CO11 Deadpool"] = {vp=6, isHero=true, isBoss=true, cost=9,},~
    ["CO2 Madame Gao"] = {vp=5, isVillain=true, isBoss=true, cost=9, id=6400},
    ["IW5 Sauron"] = {vp=6, isVillain=true, isBoss=true, cost=9,},
    ["RE Magneto"] = {vp=5, isVillain=true, isBoss=true, cost=9,},
    ["IW5 Homem de Ferro I.M.A."] = {vp=6, isVillain=true, isBoss=true, cost=9,},
    ["IW5 Homem de Ferro Dormammu"] = {vp=6, isVillain=true, isBoss=true, cost=9,},
    ["CO11 Namor"] = {vp=6, isHero=true, isBoss=true, cost=9,},

-- Nemesis Custo 10
    ["SP Cavaleiro Negro"] = {vp=5, isHero=true, isBoss=true, cost=10,},
    ["SP Anjo"] = {vp=5, isHero=true, isBoss=true, cost=10,},
    ["CO12 Hulk"] = {vp=5, isHero=true, isDefense=true, isBoss=true, cost=10,},
    ["CC1 Fanático"] = {vp=5, isVillain=true, isBoss=true, isDefense=true, cost=10,},
    ["RE Fanático"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["PROMO Aniquilador"] = {vp=5, isVillain=true, isBoss=true, cost=10, id=1822},
    ["TU90 Kraven"] = {vp=5, isBoss=true, cost=10, id=9584},
    ["RC Soldado Invernal"] = {vp=5, isHero=true, isBoss=true, cost=10,},
    ["TV Psylocke"] = {vp=5, isHero=true, isBoss=true, cost=10,},
    ["TU Cassandra Nova"] = {vp=5, isBoss=true, cost=10, id=8497},
    ["CO12 Elektra"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["CW2 Nova Richard Rider"] = {vp=5, isHero=true, isBoss=true, cost=9,},
    ["RE Lobisomem na Noite"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["TU90 M.O.D.O.K."] = {vp=5, isBoss=true, cost=10, id=6275},
    ["TU902 Molde Mestre"] = {vp=5, isBoss=true, cost=10,},
    ["DA Wolverine Arma X"] = {vp=5, isHero=true, isBoss=true, cost=10, id=9548},
    ["TV Mística"] = {vp=5, isVillain=true, isBoss=true, isOngoing=true, cost=10,},
    ["TU902 Demogoblin"] = {vp=5, isBoss=true, cost=10,},
    ["RE Nevasca"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["TV Duende Verde"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["TV Espadachim"] = {vp=5, isVillain=true, isBoss=true, cost=10,},
    ["PROMO Força-V"] = {vp=5, isHero=true, isBoss=true, isDefense=true, cost=10,},
    ["TU90 Senhor Sinistro"] = {vp=5, isBoss=true, isVillain=true, cost=10},
    ["RC Máquina de Combate"] = {vp=5, isHero=true, isBoss=true, cost=10,},
    ["RC Aranha Escarlate"] = {vp=5, isHero=true, isBoss=true, cost=10,},

-- Nemesis Custo 11
    ["SP Homem de Ferro"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["SP Nova Richard Rider"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["CW2 Capitã Marvel"] = {vp=6, isHero=true, isBoss=true, isDefense=true, cost=11,},
    ["IW5 Homem de Ferro Mark 1"] = {vp=7, isVillain=true, isBoss=true, cost=11,},
    ["CO12 Carnificina"] = {vp=6, isVillain=true, isAttack=true, isBoss=true, cost=11,},
    ["IW4 Terrax"] = {vp=5, isVillain=true, isBoss=true, isOngoing=true, cost=11, id=7942},
    ["CO11 Hulk"] = {vp=7, isHero=true, isBoss=true, cost=11,},
    ["RC Noturno"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["ST O Justiceiro"] = {vp=6, isHero=true, isAttack=true, isBoss=true, cost=11,},
    ["TV X-23"] = {vp=6, isVillain=true, isBoss=true, cost=11, isAttack=true,},
    ["TV Sanguessuga"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["IW1 Doutor Destino"] = {vp=5, isVillain=true, isBoss=true, cost=11, id=8388},
    ["TV Pesadelo"] = {vp=6, isVillain=true, isBoss=true, cost=11,},
    ["CW2 Hulk Vermelho General Ross"] = {vp=6, isVillain=true, isBoss=true, isAttack=true, cost=11,},
    ["PROMO Hannibal King"] = {vp=7, isHero=true, isBoss=true, cost=11,},
    ["IW2 Ômega Vermelho"] = {vp=5, isVillain=true, isBoss=true, cost=11, id=9335},
    ["CC1 Massacre"] = {vp=6, isVillain=true, isBoss=true, cost=11,},
    ["CO10 Lobisomem na Noite Terra X"] = {vp=6, isVillain=true, isBoss=true, cost=11,},
    ["CO11 Doutor Estranho"] = {vp=7, isHero=true, isBoss=true, cost=11,},
    ["IW5 Patriota de Ferro"] = {vp=7, isVillain=true, isBoss=true, cost=11,},
    ["CO12 Homem-Areia"] = {vp=6, isVillain=true, isBoss=true, cost=11,},
    ["IW4 Mística"] = {vp=5, isVillain=true, isBoss=true, cost=11, id=4402},
    ["RE Legião"] = {vp=6, isVillain=true, isBoss=true, cost=11,},
    ["RC Gata Negra"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["IW5 Sentinela de Ferro"] = {vp=7, isVillain=true, isBoss=true, cost=11,},
    ["PROMO Morfo"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["RC Gwen-Aranha"] = {vp=6, isHero=true, isBoss=true, cost=11,},
    ["IW5 Homem de Ferro Bebê"] = {vp=7, isVillain=true, isBoss=true, cost=11,},
    ["IW2 Cull Obsidian"] = {vp=5, isVillain=true, isBoss=true, cost=11, id=4379},
    ["IW2 Hipérion"] = {vp=5, isVillain=true, isBoss=true, cost=11, id=5807},
   
-- Nemesis Custo 12
    ["SP Capitã Marvel"] = {vp=6, isHero=true, isBoss=true, isDefense=true, cost=12,},
    ["SP Namor"] = {vp=6, isHero=true, isBoss=true, cost=12,},
    ["CO9 Maestro"] = {vp=6, isVillain=true, isBoss=true, isDefense=true, cost=12,},
    ["TV Mary Tifoide"] = {vp=6, isVillain=true, isBoss=true, cost=12,},
    ["CW2 Hulk"] = {vp=6, isHero=true, isBoss=true, cost=12,},
    ["IW3 Nova Ômega Garthan Saal"] = {vp=6, isVillain=true, isBoss=true, isPowerRing=true, cost=12, id=7824},
    ["RC Demolidor"] = {vp=6, isHero=true, isBoss=true, cost=12,},
    ["IW2 Destruidor"] = {vp=6, isVillain=true, isBoss=true, cost=12, id=6362},
    ["CO5 Makkari"] = {vp=6, isHero=true, isBoss=true, cost=12, id=5463},
    ["CO2 Flecha Certeira"] = {vp=6, isVillain=true, isBoss=true, isDefense=true, cost=12, id=5870},
    ["TV Avalanche"] = {vp=6, isVillain=true, isBoss=true, cost=12,},
    ["CW2 Abominável"] = {vp=6, isVillain=true, isBoss=true, isAttack=true, cost=12,},
    ["IW2 Homem-Absorvente"] = {vp=6, isVillain=true, isBoss=true, cost=12, id=8351},
    ["IW2 Abominável"] = {vp=6, isVillain=true, isBoss=true, cost=12, id=9042},
    ["IW4 Hela"] = {vp=6, isVillain=true, isBoss=true, cost=12, id=5649},
    ["TV Luke Cage"] = {vp=6, isHero=true, isBoss=true, cost=12,},
    ["MS Serpente da Lua"] = {vp=7, isHero=true, isBoss=true, cost=12,},
    
-- Nemesis Custo 13
    ["IW3 Rocha Lunar"] = {vp=6, isVillain=true, isBoss=true, cost=13, id=4581},
    ["DA Hulk"] = {vp=6, isHero=true, isBoss=true, cost=13, id=7331},
    ["IW3 Barão Zemo"] = {vp=6, isVillain=true, isBoss=true, cost=13, id=7153},
    ["CO9 Celestiais"] = {vp=6, isVillain=true, isBoss=true, cost=13,},
    ["CO1 Massacre"] = {vp=6, isVillain=true, isBoss=true, cost=13, id=9924},
    ["IW2 Hulk Zumbi"] = {vp=6, isVillain=true, isBoss=true, cost=13, id=5616},

-- Nemesis Custo 14/15
    ["CO10 Mercúrio"] = {vp=7, isVillain=true, isBoss=true, cost=15,},
    ["TV Mandarim"] = {vp=7, isVillain=true, isBoss=true, cost=14,},
    ["TV Demolidor Boss"] = {vp=7, isHero=true, isBoss=true, cost=14,},
    ["CC1 Dormammu"] = {vp=7, isVillain=true, isBoss=true, cost=14,},
    ["CO2 Galactus"] = {vp=7, isVillain=true, isBoss=true, cost=14, id=4498},
    ["CO1 Knull"] = {vp=7, isVillain=true, isBoss=true, cost=15, id=9811},
    ["RC Homem de Ferro"] = {vp=7, isHero=true, isBoss=true, cost=14,},
    ["TV Venom"] = {vp=7, isVillain=true, isBoss=true, cost=14,},
    